<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>7 Graphical analysis of ordinary differential equations | Quantifying Life</title>
  <meta name="description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="7 Graphical analysis of ordinary differential equations | Quantifying Life" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="7 Graphical analysis of ordinary differential equations | Quantifying Life" />
  
  <meta name="twitter:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  

<meta name="author" content="Dmitry Kondrashov" />


<meta name="date" content="2021-04-01" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="linear-ordinary-differential-equations.html"/>
<link rel="next" href="random-variables-and-distributions.html"/>
<script src="libs/header-attrs-2.6/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./"> Quantifying Life (Web version) </a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Purpose and purview</a>
<ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#a-brief-motivation-of-mathematical-modeling"><i class="fa fa-check"></i><b>0.1</b> A brief motivation of mathematical modeling</a></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#purpose-of-this-book"><i class="fa fa-check"></i><b>0.2</b> Purpose of this book</a></li>
<li class="chapter" data-level="0.3" data-path="index.html"><a href="index.html#organization-of-the-book"><i class="fa fa-check"></i><b>0.3</b> Organization of the book</a></li>
</ul></li>
<li class="part"><span><b>I The Basics</b></span></li>
<li class="chapter" data-level="1" data-path="arithmetic-and-variables.html"><a href="arithmetic-and-variables.html"><i class="fa fa-check"></i><b>1</b> Arithmetic and variables</a>
<ul>
<li class="chapter" data-level="1.1" data-path="arithmetic-and-variables.html"><a href="arithmetic-and-variables.html#sec:bio1"><i class="fa fa-check"></i><b>1.1</b> Blood circulation and mathematical modeling</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="arithmetic-and-variables.html"><a href="arithmetic-and-variables.html#galens-theory-of-blood"><i class="fa fa-check"></i><b>1.1.1</b> Galen’s theory of blood</a></li>
<li class="chapter" data-level="1.1.2" data-path="arithmetic-and-variables.html"><a href="arithmetic-and-variables.html#mathematical-testing-of-the-theory"><i class="fa fa-check"></i><b>1.1.2</b> Mathematical testing of the theory</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="arithmetic-and-variables.html"><a href="arithmetic-and-variables.html#sec:math1"><i class="fa fa-check"></i><b>1.2</b> Parameters and variables in models</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="arithmetic-and-variables.html"><a href="arithmetic-and-variables.html#discrete-state-variables-genetics"><i class="fa fa-check"></i><b>1.2.1</b> discrete state variables: genetics</a></li>
<li class="chapter" data-level="1.2.2" data-path="arithmetic-and-variables.html"><a href="arithmetic-and-variables.html#discrete-state-variables-population"><i class="fa fa-check"></i><b>1.2.2</b> discrete state variables: population</a></li>
<li class="chapter" data-level="1.2.3" data-path="arithmetic-and-variables.html"><a href="arithmetic-and-variables.html#continuous-state-variables-concentration"><i class="fa fa-check"></i><b>1.2.3</b> continuous state variables: concentration</a></li>
<li class="chapter" data-level="1.2.4" data-path="arithmetic-and-variables.html"><a href="arithmetic-and-variables.html#multiple-variables-in-medicine"><i class="fa fa-check"></i><b>1.2.4</b> multiple variables in medicine</a></li>
<li class="chapter" data-level="1.2.5" data-path="arithmetic-and-variables.html"><a href="arithmetic-and-variables.html#discussion-questions"><i class="fa fa-check"></i><b>1.2.5</b> Discussion questions</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="arithmetic-and-variables.html"><a href="arithmetic-and-variables.html#first-steps-in-r"><i class="fa fa-check"></i><b>1.3</b> First steps in R</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="arithmetic-and-variables.html"><a href="arithmetic-and-variables.html#r-markdown-and-r-studio"><i class="fa fa-check"></i><b>1.3.1</b> R Markdown and R Studio</a></li>
<li class="chapter" data-level="1.3.2" data-path="arithmetic-and-variables.html"><a href="arithmetic-and-variables.html#numbers-and-arithmetic-operations"><i class="fa fa-check"></i><b>1.3.2</b> numbers and arithmetic operations</a></li>
<li class="chapter" data-level="1.3.3" data-path="arithmetic-and-variables.html"><a href="arithmetic-and-variables.html#r-coding-exercises"><i class="fa fa-check"></i><b>1.3.3</b> R Coding Exercises</a></li>
<li class="chapter" data-level="1.3.4" data-path="arithmetic-and-variables.html"><a href="arithmetic-and-variables.html#variable-assignment"><i class="fa fa-check"></i><b>1.3.4</b> variable assignment</a></li>
<li class="chapter" data-level="1.3.5" data-path="arithmetic-and-variables.html"><a href="arithmetic-and-variables.html#r-coding-exercises-1"><i class="fa fa-check"></i><b>1.3.5</b> R Coding Exercises</a></li>
<li class="chapter" data-level="1.3.6" data-path="arithmetic-and-variables.html"><a href="arithmetic-and-variables.html#exercises"><i class="fa fa-check"></i><b>1.3.6</b> Exercises:</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="arithmetic-and-variables.html"><a href="arithmetic-and-variables.html#r-assignment"><i class="fa fa-check"></i><b>1.4</b> R Assignment</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="functions-and-their-graphs.html"><a href="functions-and-their-graphs.html"><i class="fa fa-check"></i><b>2</b> Functions and their graphs</a>
<ul>
<li class="chapter" data-level="2.1" data-path="functions-and-their-graphs.html"><a href="functions-and-their-graphs.html#sec:model2"><i class="fa fa-check"></i><b>2.1</b> Dimensions of quantities</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="functions-and-their-graphs.html"><a href="functions-and-their-graphs.html#exercises-1"><i class="fa fa-check"></i><b>2.1.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="functions-and-their-graphs.html"><a href="functions-and-their-graphs.html#sec:math2"><i class="fa fa-check"></i><b>2.2</b> Functions and their graphs</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="functions-and-their-graphs.html"><a href="functions-and-their-graphs.html#linear-and-exponential-functions"><i class="fa fa-check"></i><b>2.2.1</b> linear and exponential functions</a></li>
<li class="chapter" data-level="2.2.2" data-path="functions-and-their-graphs.html"><a href="functions-and-their-graphs.html#exercises-2"><i class="fa fa-check"></i><b>2.2.2</b> Exercises</a></li>
<li class="chapter" data-level="2.2.3" data-path="functions-and-their-graphs.html"><a href="functions-and-their-graphs.html#rational-and-logistic-functions"><i class="fa fa-check"></i><b>2.2.3</b> rational and logistic functions</a></li>
<li class="chapter" data-level="2.2.4" data-path="functions-and-their-graphs.html"><a href="functions-and-their-graphs.html#exercises-3"><i class="fa fa-check"></i><b>2.2.4</b> Exercises:</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="functions-and-their-graphs.html"><a href="functions-and-their-graphs.html#vectors-and-plotting-in-r"><i class="fa fa-check"></i><b>2.3</b> Vectors and plotting in R</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="functions-and-their-graphs.html"><a href="functions-and-their-graphs.html#writing-scripts-and-calling-functions"><i class="fa fa-check"></i><b>2.3.1</b> writing scripts and calling functions</a></li>
<li class="chapter" data-level="2.3.2" data-path="functions-and-their-graphs.html"><a href="functions-and-their-graphs.html#vector-variables"><i class="fa fa-check"></i><b>2.3.2</b> vector variables</a></li>
<li class="chapter" data-level="2.3.3" data-path="functions-and-their-graphs.html"><a href="functions-and-their-graphs.html#calculations-with-vector-variables"><i class="fa fa-check"></i><b>2.3.3</b> calculations with vector variables</a></li>
<li class="chapter" data-level="2.3.4" data-path="functions-and-their-graphs.html"><a href="functions-and-their-graphs.html#exercises-4"><i class="fa fa-check"></i><b>2.3.4</b> Exercises</a></li>
<li class="chapter" data-level="2.3.5" data-path="functions-and-their-graphs.html"><a href="functions-and-their-graphs.html#plotting-with-vectors"><i class="fa fa-check"></i><b>2.3.5</b> Plotting with vectors</a></li>
<li class="chapter" data-level="2.3.6" data-path="functions-and-their-graphs.html"><a href="functions-and-their-graphs.html#exercises-5"><i class="fa fa-check"></i><b>2.3.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="functions-and-their-graphs.html"><a href="functions-and-their-graphs.html#rates-of-biochemical-reactions"><i class="fa fa-check"></i><b>2.4</b> Rates of biochemical reactions</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="functions-and-their-graphs.html"><a href="functions-and-their-graphs.html#constant-zeroth-order-kinetics"><i class="fa fa-check"></i><b>2.4.1</b> Constant (zeroth-order) kinetics</a></li>
<li class="chapter" data-level="2.4.2" data-path="functions-and-their-graphs.html"><a href="functions-and-their-graphs.html#first-order-kinetics"><i class="fa fa-check"></i><b>2.4.2</b> First-order kinetics</a></li>
<li class="chapter" data-level="2.4.3" data-path="functions-and-their-graphs.html"><a href="functions-and-their-graphs.html#michaelis-menten-model-of-enzyme-kinetics"><i class="fa fa-check"></i><b>2.4.3</b> Michaelis-Menten model of enzyme kinetics </a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="functions-and-their-graphs.html"><a href="functions-and-their-graphs.html#r-assignment-1"><i class="fa fa-check"></i><b>2.5</b> R Assignment</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="describing-data-sets.html"><a href="describing-data-sets.html"><i class="fa fa-check"></i><b>3</b> Describing data sets</a>
<ul>
<li class="chapter" data-level="3.1" data-path="describing-data-sets.html"><a href="describing-data-sets.html#mutations-and-their-rates"><i class="fa fa-check"></i><b>3.1</b> Mutations and their rates</a></li>
<li class="chapter" data-level="3.2" data-path="describing-data-sets.html"><a href="describing-data-sets.html#describing-data-sets-1"><i class="fa fa-check"></i><b>3.2</b> Describing data sets</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="describing-data-sets.html"><a href="describing-data-sets.html#central-value-of-a-data-set"><i class="fa fa-check"></i><b>3.2.1</b> central value of a data set</a></li>
<li class="chapter" data-level="3.2.2" data-path="describing-data-sets.html"><a href="describing-data-sets.html#exercises-6"><i class="fa fa-check"></i><b>3.2.2</b> Exercises</a></li>
<li class="chapter" data-level="3.2.3" data-path="describing-data-sets.html"><a href="describing-data-sets.html#spread-of-a-data-set"><i class="fa fa-check"></i><b>3.2.3</b> spread of a data set</a></li>
<li class="chapter" data-level="3.2.4" data-path="describing-data-sets.html"><a href="describing-data-sets.html#exercises-7"><i class="fa fa-check"></i><b>3.2.4</b> Exercises:</a></li>
<li class="chapter" data-level="3.2.5" data-path="describing-data-sets.html"><a href="describing-data-sets.html#describing-data-sets-in-graphs"><i class="fa fa-check"></i><b>3.2.5</b> describing data sets in graphs</a></li>
<li class="chapter" data-level="3.2.6" data-path="describing-data-sets.html"><a href="describing-data-sets.html#exercises-8"><i class="fa fa-check"></i><b>3.2.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="describing-data-sets.html"><a href="describing-data-sets.html#working-with-data-in-r"><i class="fa fa-check"></i><b>3.3</b> Working with data in R</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="describing-data-sets.html"><a href="describing-data-sets.html#reading-in-data-into-data-frames"><i class="fa fa-check"></i><b>3.3.1</b> reading in data into data frames</a></li>
<li class="chapter" data-level="3.3.2" data-path="describing-data-sets.html"><a href="describing-data-sets.html#descriptive-statistics"><i class="fa fa-check"></i><b>3.3.2</b> descriptive statistics</a></li>
<li class="chapter" data-level="3.3.3" data-path="describing-data-sets.html"><a href="describing-data-sets.html#exercises-9"><i class="fa fa-check"></i><b>3.3.3</b> Exercises:</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="describing-data-sets.html"><a href="describing-data-sets.html#r-assignment-2"><i class="fa fa-check"></i><b>3.4</b> R Assignment</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="linear-regression.html"><a href="linear-regression.html"><i class="fa fa-check"></i><b>4</b> Linear regression</a>
<ul>
<li class="chapter" data-level="4.1" data-path="linear-regression.html"><a href="linear-regression.html#linear-relationship-between-two-variables"><i class="fa fa-check"></i><b>4.1</b> Linear relationship between two variables</a></li>
<li class="chapter" data-level="4.2" data-path="linear-regression.html"><a href="linear-regression.html#linear-least-squares-fitting"><i class="fa fa-check"></i><b>4.2</b> Linear least-squares fitting</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="linear-regression.html"><a href="linear-regression.html#sum-of-squared-errors"><i class="fa fa-check"></i><b>4.2.1</b> sum of squared errors</a></li>
<li class="chapter" data-level="4.2.2" data-path="linear-regression.html"><a href="linear-regression.html#best-fit-slope-and-intercept"><i class="fa fa-check"></i><b>4.2.2</b> best-fit slope and intercept</a></li>
<li class="chapter" data-level="4.2.3" data-path="linear-regression.html"><a href="linear-regression.html#execises"><i class="fa fa-check"></i><b>4.2.3</b> Execises</a></li>
<li class="chapter" data-level="4.2.4" data-path="linear-regression.html"><a href="linear-regression.html#correlation-and-goodness-of-fit"><i class="fa fa-check"></i><b>4.2.4</b> correlation and goodness of fit}</a></li>
<li class="chapter" data-level="4.2.5" data-path="linear-regression.html"><a href="linear-regression.html#exercises-10"><i class="fa fa-check"></i><b>4.2.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="linear-regression.html"><a href="linear-regression.html#linear-regression-using-r"><i class="fa fa-check"></i><b>4.3</b> Linear regression using R</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="linear-regression.html"><a href="linear-regression.html#exercises-11"><i class="fa fa-check"></i><b>4.3.1</b> Exercises:</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="linear-regression.html"><a href="linear-regression.html#regression-to-the-mean"><i class="fa fa-check"></i><b>4.4</b> Regression to the mean</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="linear-regression.html"><a href="linear-regression.html#discussion-questions-1"><i class="fa fa-check"></i><b>4.4.1</b> Discussion questions</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="linear-regression.html"><a href="linear-regression.html#r-assignment-3"><i class="fa fa-check"></i><b>4.5</b> R Assignment</a></li>
</ul></li>
<li class="part"><span><b>II Things that change over time</b></span></li>
<li class="chapter" data-level="5" data-path="linear-difference-equations.html"><a href="linear-difference-equations.html"><i class="fa fa-check"></i><b>5</b> Linear difference equations</a>
<ul>
<li class="chapter" data-level="5.1" data-path="linear-difference-equations.html"><a href="linear-difference-equations.html#discrete-time-population-models"><i class="fa fa-check"></i><b>5.1</b> Discrete time population models</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="linear-difference-equations.html"><a href="linear-difference-equations.html#static-population"><i class="fa fa-check"></i><b>5.1.1</b> static population</a></li>
<li class="chapter" data-level="5.1.2" data-path="linear-difference-equations.html"><a href="linear-difference-equations.html#exponential-population-growth"><i class="fa fa-check"></i><b>5.1.2</b> exponential population growth</a></li>
<li class="chapter" data-level="5.1.3" data-path="linear-difference-equations.html"><a href="linear-difference-equations.html#population-with-births-and-deaths"><i class="fa fa-check"></i><b>5.1.3</b> population with births and deaths</a></li>
<li class="chapter" data-level="5.1.4" data-path="linear-difference-equations.html"><a href="linear-difference-equations.html#dimensions-of-birth-and-death-rates"><i class="fa fa-check"></i><b>5.1.4</b> dimensions of birth and death rates</a></li>
<li class="chapter" data-level="5.1.5" data-path="linear-difference-equations.html"><a href="linear-difference-equations.html#linear-demographic-models"><i class="fa fa-check"></i><b>5.1.5</b> linear demographic models</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="linear-difference-equations.html"><a href="linear-difference-equations.html#solutions-of-linear-difference-models"><i class="fa fa-check"></i><b>5.2</b> Solutions of linear difference models</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="linear-difference-equations.html"><a href="linear-difference-equations.html#simple-linear-models"><i class="fa fa-check"></i><b>5.2.1</b> simple linear models</a></li>
<li class="chapter" data-level="5.2.2" data-path="linear-difference-equations.html"><a href="linear-difference-equations.html#models-with-a-constant-term"><i class="fa fa-check"></i><b>5.2.2</b> models with a constant term</a></li>
<li class="chapter" data-level="5.2.3" data-path="linear-difference-equations.html"><a href="linear-difference-equations.html#population-growth-and-decline"><i class="fa fa-check"></i><b>5.2.3</b> population growth and decline</a></li>
<li class="chapter" data-level="5.2.4" data-path="linear-difference-equations.html"><a href="linear-difference-equations.html#exercises-12"><i class="fa fa-check"></i><b>5.2.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="linear-difference-equations.html"><a href="linear-difference-equations.html#numerical-solutions-in-r"><i class="fa fa-check"></i><b>5.3</b> Numerical solutions in R</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="linear-difference-equations.html"><a href="linear-difference-equations.html#for-loops"><i class="fa fa-check"></i><b>5.3.1</b> for loops</a></li>
<li class="chapter" data-level="5.3.2" data-path="linear-difference-equations.html"><a href="linear-difference-equations.html#using-vectors-with-loops"><i class="fa fa-check"></i><b>5.3.2</b> using vectors with loops</a></li>
<li class="chapter" data-level="5.3.3" data-path="linear-difference-equations.html"><a href="linear-difference-equations.html#exercises-13"><i class="fa fa-check"></i><b>5.3.3</b> Exercises:</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="linear-difference-equations.html"><a href="linear-difference-equations.html#r-assignment-4"><i class="fa fa-check"></i><b>5.4</b> R Assignment</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="linear-ordinary-differential-equations.html"><a href="linear-ordinary-differential-equations.html"><i class="fa fa-check"></i><b>6</b> Linear ordinary differential equations</a>
<ul>
<li class="chapter" data-level="6.1" data-path="linear-ordinary-differential-equations.html"><a href="linear-ordinary-differential-equations.html#building-differential-equations"><i class="fa fa-check"></i><b>6.1</b> Building differential equations</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="linear-ordinary-differential-equations.html"><a href="linear-ordinary-differential-equations.html#from-discrete-time-to-continuous"><i class="fa fa-check"></i><b>6.1.1</b> from discrete time to continuous</a></li>
<li class="chapter" data-level="6.1.2" data-path="linear-ordinary-differential-equations.html"><a href="linear-ordinary-differential-equations.html#exercises-14"><i class="fa fa-check"></i><b>6.1.2</b> Exercises</a></li>
<li class="chapter" data-level="6.1.3" data-path="linear-ordinary-differential-equations.html"><a href="linear-ordinary-differential-equations.html#growth-proportional-to-population-size"><i class="fa fa-check"></i><b>6.1.3</b> growth proportional to population size</a></li>
<li class="chapter" data-level="6.1.4" data-path="linear-ordinary-differential-equations.html"><a href="linear-ordinary-differential-equations.html#chemical-kinetics"><i class="fa fa-check"></i><b>6.1.4</b> chemical kinetics</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="linear-ordinary-differential-equations.html"><a href="linear-ordinary-differential-equations.html#solutions-of-ordinary-differential-equations"><i class="fa fa-check"></i><b>6.2</b> Solutions of ordinary differential equations</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="linear-ordinary-differential-equations.html"><a href="linear-ordinary-differential-equations.html#separate-and-integrate-method"><i class="fa fa-check"></i><b>6.2.1</b> separate and integrate method</a></li>
<li class="chapter" data-level="6.2.2" data-path="linear-ordinary-differential-equations.html"><a href="linear-ordinary-differential-equations.html#behavior-of-solutions-of-linear-odes"><i class="fa fa-check"></i><b>6.2.2</b> behavior of solutions of linear ODEs</a></li>
<li class="chapter" data-level="6.2.3" data-path="linear-ordinary-differential-equations.html"><a href="linear-ordinary-differential-equations.html#solutions-of-nonhomogeneous-odes"><i class="fa fa-check"></i><b>6.2.3</b> solutions of nonhomogeneous ODEs</a></li>
<li class="chapter" data-level="6.2.4" data-path="linear-ordinary-differential-equations.html"><a href="linear-ordinary-differential-equations.html#exercises-15"><i class="fa fa-check"></i><b>6.2.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="linear-ordinary-differential-equations.html"><a href="linear-ordinary-differential-equations.html#numeric-solutions-and-the-forward-euler-method"><i class="fa fa-check"></i><b>6.3</b> Numeric solutions and the Forward Euler method</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="linear-ordinary-differential-equations.html"><a href="linear-ordinary-differential-equations.html#exercises-16"><i class="fa fa-check"></i><b>6.3.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="linear-ordinary-differential-equations.html"><a href="linear-ordinary-differential-equations.html#forward-euler-method-in-r"><i class="fa fa-check"></i><b>6.4</b> Forward Euler method in R</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="linear-ordinary-differential-equations.html"><a href="linear-ordinary-differential-equations.html#implementation"><i class="fa fa-check"></i><b>6.4.1</b> implementation</a></li>
<li class="chapter" data-level="6.4.2" data-path="linear-ordinary-differential-equations.html"><a href="linear-ordinary-differential-equations.html#exercises-17"><i class="fa fa-check"></i><b>6.4.2</b> Exercises</a></li>
<li class="chapter" data-level="6.4.3" data-path="linear-ordinary-differential-equations.html"><a href="linear-ordinary-differential-equations.html#error-analysis"><i class="fa fa-check"></i><b>6.4.3</b> error analysis</a></li>
<li class="chapter" data-level="6.4.4" data-path="linear-ordinary-differential-equations.html"><a href="linear-ordinary-differential-equations.html#exercises-18"><i class="fa fa-check"></i><b>6.4.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="linear-ordinary-differential-equations.html"><a href="linear-ordinary-differential-equations.html#applications-of-linear-ode-models"><i class="fa fa-check"></i><b>6.5</b> Applications of linear ODE models</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="linear-ordinary-differential-equations.html"><a href="linear-ordinary-differential-equations.html#model-of-pharmacokinetics"><i class="fa fa-check"></i><b>6.5.1</b> model of pharmacokinetics</a></li>
<li class="chapter" data-level="6.5.2" data-path="linear-ordinary-differential-equations.html"><a href="linear-ordinary-differential-equations.html#discussion-questions-2"><i class="fa fa-check"></i><b>6.5.2</b> Discussion questions</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="linear-ordinary-differential-equations.html"><a href="linear-ordinary-differential-equations.html#r-assignment-5"><i class="fa fa-check"></i><b>6.6</b> R Assignment</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="graphical-analysis-of-ordinary-differential-equations.html"><a href="graphical-analysis-of-ordinary-differential-equations.html"><i class="fa fa-check"></i><b>7</b> Graphical analysis of ordinary differential equations</a>
<ul>
<li class="chapter" data-level="7.1" data-path="graphical-analysis-of-ordinary-differential-equations.html"><a href="graphical-analysis-of-ordinary-differential-equations.html#building-nonlinear-odes"><i class="fa fa-check"></i><b>7.1</b> Building nonlinear ODEs</a></li>
<li class="chapter" data-level="7.2" data-path="graphical-analysis-of-ordinary-differential-equations.html"><a href="graphical-analysis-of-ordinary-differential-equations.html#qualitative-analysis-of-odes"><i class="fa fa-check"></i><b>7.2</b> Qualitative analysis of ODEs</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="graphical-analysis-of-ordinary-differential-equations.html"><a href="graphical-analysis-of-ordinary-differential-equations.html#graphical-analysis-of-the-defining-function"><i class="fa fa-check"></i><b>7.2.1</b> graphical analysis of the defining function</a></li>
<li class="chapter" data-level="7.2.2" data-path="graphical-analysis-of-ordinary-differential-equations.html"><a href="graphical-analysis-of-ordinary-differential-equations.html#fixed-points-and-stability"><i class="fa fa-check"></i><b>7.2.2</b> fixed points and stability</a></li>
<li class="chapter" data-level="7.2.3" data-path="graphical-analysis-of-ordinary-differential-equations.html"><a href="graphical-analysis-of-ordinary-differential-equations.html#outline-of-qualitative-analysis-of-an-ode"><i class="fa fa-check"></i><b>7.2.3</b> Outline of qualitative analysis of an ODE</a></li>
<li class="chapter" data-level="7.2.4" data-path="graphical-analysis-of-ordinary-differential-equations.html"><a href="graphical-analysis-of-ordinary-differential-equations.html#exercises-19"><i class="fa fa-check"></i><b>7.2.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="graphical-analysis-of-ordinary-differential-equations.html"><a href="graphical-analysis-of-ordinary-differential-equations.html#functions-in-r"><i class="fa fa-check"></i><b>7.3</b> Functions in R</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="graphical-analysis-of-ordinary-differential-equations.html"><a href="graphical-analysis-of-ordinary-differential-equations.html#defining-a-function"><i class="fa fa-check"></i><b>7.3.1</b> defining a function</a></li>
<li class="chapter" data-level="7.3.2" data-path="graphical-analysis-of-ordinary-differential-equations.html"><a href="graphical-analysis-of-ordinary-differential-equations.html#calling-a-function"><i class="fa fa-check"></i><b>7.3.2</b> calling a function</a></li>
<li class="chapter" data-level="7.3.3" data-path="graphical-analysis-of-ordinary-differential-equations.html"><a href="graphical-analysis-of-ordinary-differential-equations.html#using-a-function-to-solve-a-difference-equation"><i class="fa fa-check"></i><b>7.3.3</b> using a function to solve a difference equation</a></li>
<li class="chapter" data-level="7.3.4" data-path="graphical-analysis-of-ordinary-differential-equations.html"><a href="graphical-analysis-of-ordinary-differential-equations.html#exercises-20"><i class="fa fa-check"></i><b>7.3.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="graphical-analysis-of-ordinary-differential-equations.html"><a href="graphical-analysis-of-ordinary-differential-equations.html#modeling-the-spread-of-infectious-disease-spread"><i class="fa fa-check"></i><b>7.4</b> Modeling the spread of infectious disease spread</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="graphical-analysis-of-ordinary-differential-equations.html"><a href="graphical-analysis-of-ordinary-differential-equations.html#discussion"><i class="fa fa-check"></i><b>7.4.1</b> Discussion</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="graphical-analysis-of-ordinary-differential-equations.html"><a href="graphical-analysis-of-ordinary-differential-equations.html#r-assignment-6"><i class="fa fa-check"></i><b>7.5</b> R Assignment</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="graphical-analysis-of-ordinary-differential-equations.html"><a href="graphical-analysis-of-ordinary-differential-equations.html#logistic-population-model"><i class="fa fa-check"></i><b>7.5.1</b> logistic population model</a></li>
<li class="chapter" data-level="7.5.2" data-path="graphical-analysis-of-ordinary-differential-equations.html"><a href="graphical-analysis-of-ordinary-differential-equations.html#sis-model-of-infectious-disease"><i class="fa fa-check"></i><b>7.5.2</b> SIS model of infectious disease</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>III Randomness in observations</b></span></li>
<li class="chapter" data-level="8" data-path="random-variables-and-distributions.html"><a href="random-variables-and-distributions.html"><i class="fa fa-check"></i><b>8</b> Random variables and distributions</a>
<ul>
<li class="chapter" data-level="8.1" data-path="random-variables-and-distributions.html"><a href="random-variables-and-distributions.html#random-variables-and-distributions-1"><i class="fa fa-check"></i><b>8.1</b> Random variables and distributions</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="random-variables-and-distributions.html"><a href="random-variables-and-distributions.html#definition-of-probability"><i class="fa fa-check"></i><b>8.1.1</b> definition of probability</a></li>
<li class="chapter" data-level="8.1.2" data-path="random-variables-and-distributions.html"><a href="random-variables-and-distributions.html#axioms-of-probability"><i class="fa fa-check"></i><b>8.1.2</b> axioms of probability</a></li>
<li class="chapter" data-level="8.1.3" data-path="random-variables-and-distributions.html"><a href="random-variables-and-distributions.html#random-variables"><i class="fa fa-check"></i><b>8.1.3</b> random variables</a></li>
<li class="chapter" data-level="8.1.4" data-path="random-variables-and-distributions.html"><a href="random-variables-and-distributions.html#expectation-of-random-variables"><i class="fa fa-check"></i><b>8.1.4</b> expectation of random variables</a></li>
<li class="chapter" data-level="8.1.5" data-path="random-variables-and-distributions.html"><a href="random-variables-and-distributions.html#variance-of-random-variables"><i class="fa fa-check"></i><b>8.1.5</b> variance of random variables</a></li>
<li class="chapter" data-level="8.1.6" data-path="random-variables-and-distributions.html"><a href="random-variables-and-distributions.html#exercises-21"><i class="fa fa-check"></i><b>8.1.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="random-variables-and-distributions.html"><a href="random-variables-and-distributions.html#examples-of-distributions"><i class="fa fa-check"></i><b>8.2</b> Examples of distributions</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="random-variables-and-distributions.html"><a href="random-variables-and-distributions.html#uniform-distribution"><i class="fa fa-check"></i><b>8.2.1</b> uniform distribution</a></li>
<li class="chapter" data-level="8.2.2" data-path="random-variables-and-distributions.html"><a href="random-variables-and-distributions.html#binomial-distribution"><i class="fa fa-check"></i><b>8.2.2</b> binomial distribution</a></li>
<li class="chapter" data-level="8.2.3" data-path="random-variables-and-distributions.html"><a href="random-variables-and-distributions.html#exercises-22"><i class="fa fa-check"></i><b>8.2.3</b> Exercises</a></li>
<li class="chapter" data-level="8.2.4" data-path="random-variables-and-distributions.html"><a href="random-variables-and-distributions.html#testing-for-mutants"><i class="fa fa-check"></i><b>8.2.4</b> testing for mutants</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="random-variables-and-distributions.html"><a href="random-variables-and-distributions.html#random-number-generators-in-r"><i class="fa fa-check"></i><b>8.3</b> Random number generators in R</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="sampling-distribution-and-estimation.html"><a href="sampling-distribution-and-estimation.html"><i class="fa fa-check"></i><b>9</b> Sampling distribution and estimation</a>
<ul>
<li class="chapter" data-level="9.1" data-path="sampling-distribution-and-estimation.html"><a href="sampling-distribution-and-estimation.html#law-of-large-numbers"><i class="fa fa-check"></i><b>9.1</b> Law of large numbers</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="sampling-distribution-and-estimation.html"><a href="sampling-distribution-and-estimation.html#sample-mean"><i class="fa fa-check"></i><b>9.1.1</b> sample mean</a></li>
<li class="chapter" data-level="9.1.2" data-path="sampling-distribution-and-estimation.html"><a href="sampling-distribution-and-estimation.html#sample-size-and-standard-error"><i class="fa fa-check"></i><b>9.1.2</b> sample size and standard error</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="sampling-distribution-and-estimation.html"><a href="sampling-distribution-and-estimation.html#central-limit-theorem"><i class="fa fa-check"></i><b>9.2</b> Central limit theorem</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="sampling-distribution-and-estimation.html"><a href="sampling-distribution-and-estimation.html#normal-distribution"><i class="fa fa-check"></i><b>9.2.1</b> normal distribution</a></li>
<li class="chapter" data-level="9.2.2" data-path="sampling-distribution-and-estimation.html"><a href="sampling-distribution-and-estimation.html#confidence-intervals"><i class="fa fa-check"></i><b>9.2.2</b> confidence intervals</a></li>
<li class="chapter" data-level="9.2.3" data-path="sampling-distribution-and-estimation.html"><a href="sampling-distribution-and-estimation.html#estimating-relative-risk"><i class="fa fa-check"></i><b>9.2.3</b> estimating relative risk</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="sampling-distribution-and-estimation.html"><a href="sampling-distribution-and-estimation.html#sampling-and-confidence-intervals-in-r"><i class="fa fa-check"></i><b>9.3</b> Sampling and confidence intervals in R</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="sampling-distribution-and-estimation.html"><a href="sampling-distribution-and-estimation.html#computing-confidence-intervals"><i class="fa fa-check"></i><b>9.3.1</b> computing confidence intervals</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="independence.html"><a href="independence.html"><i class="fa fa-check"></i><b>10</b> Independence</a>
<ul>
<li class="chapter" data-level="10.1" data-path="independence.html"><a href="independence.html#contingency-tables-to-summarize-data"><i class="fa fa-check"></i><b>10.1</b> Contingency tables to summarize data</a></li>
<li class="chapter" data-level="10.2" data-path="independence.html"><a href="independence.html#conditional-probability"><i class="fa fa-check"></i><b>10.2</b> Conditional probability</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="independence.html"><a href="independence.html#exercises-23"><i class="fa fa-check"></i><b>10.2.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="independence.html"><a href="independence.html#independence-of-events"><i class="fa fa-check"></i><b>10.3</b> Independence of events</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="independence.html"><a href="independence.html#exercises-24"><i class="fa fa-check"></i><b>10.3.1</b> Exercises</a></li>
<li class="chapter" data-level="10.3.2" data-path="independence.html"><a href="independence.html#product-rule"><i class="fa fa-check"></i><b>10.3.2</b> product rule</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="independence.html"><a href="independence.html#independence-of-variables"><i class="fa fa-check"></i><b>10.4</b> Independence of variables</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html"><i class="fa fa-check"></i><b>11</b> Hypothesis testing</a>
<ul>
<li class="chapter" data-level="11.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#terminology-and-quality-measures"><i class="fa fa-check"></i><b>11.1</b> Terminology and quality measures</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#positives-and-negatives"><i class="fa fa-check"></i><b>11.1.1</b> positives and negatives</a></li>
<li class="chapter" data-level="11.1.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#types-of-errors"><i class="fa fa-check"></i><b>11.1.2</b> types of errors</a></li>
<li class="chapter" data-level="11.1.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#test-quality-measures"><i class="fa fa-check"></i><b>11.1.3</b> test quality measures</a></li>
<li class="chapter" data-level="11.1.4" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#exercises-25"><i class="fa fa-check"></i><b>11.1.4</b> Exercises</a></li>
<li class="chapter" data-level="11.1.5" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#rejecting-the-null-hypothesis"><i class="fa fa-check"></i><b>11.1.5</b> rejecting the null hypothesis</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#chi-squared-test"><i class="fa fa-check"></i><b>11.2</b> Chi-squared test</a></li>
<li class="chapter" data-level="11.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#hypothesis-testing-in-r"><i class="fa fa-check"></i><b>11.3</b> Hypothesis testing in R</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#example-with-data"><i class="fa fa-check"></i><b>11.3.1</b> example with data</a></li>
<li class="chapter" data-level="11.3.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#stop-and-frisk-and-race"><i class="fa fa-check"></i><b>11.3.2</b> stop-and-frisk and race</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="prior-knowledge-and-bayesian-thinking.html"><a href="prior-knowledge-and-bayesian-thinking.html"><i class="fa fa-check"></i><b>12</b> Prior knowledge and Bayesian thinking</a>
<ul>
<li class="chapter" data-level="12.1" data-path="prior-knowledge-and-bayesian-thinking.html"><a href="prior-knowledge-and-bayesian-thinking.html#prior-knowledge"><i class="fa fa-check"></i><b>12.1</b> Prior knowledge</a></li>
<li class="chapter" data-level="12.2" data-path="prior-knowledge-and-bayesian-thinking.html"><a href="prior-knowledge-and-bayesian-thinking.html#bayes-formula"><i class="fa fa-check"></i><b>12.2</b> Bayes’ formula</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="prior-knowledge-and-bayesian-thinking.html"><a href="prior-knowledge-and-bayesian-thinking.html#positive-and-negative-predictive-values"><i class="fa fa-check"></i><b>12.2.1</b> positive and negative predictive values</a></li>
<li class="chapter" data-level="12.2.2" data-path="prior-knowledge-and-bayesian-thinking.html"><a href="prior-knowledge-and-bayesian-thinking.html#exercises-26"><i class="fa fa-check"></i><b>12.2.2</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="prior-knowledge-and-bayesian-thinking.html"><a href="prior-knowledge-and-bayesian-thinking.html#applications-of-bayesian-thinking"><i class="fa fa-check"></i><b>12.3</b> Applications of Bayesian thinking</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="prior-knowledge-and-bayesian-thinking.html"><a href="prior-knowledge-and-bayesian-thinking.html#when-too-much-testing-is-bad"><i class="fa fa-check"></i><b>12.3.1</b> when too much testing is bad</a></li>
<li class="chapter" data-level="12.3.2" data-path="prior-knowledge-and-bayesian-thinking.html"><a href="prior-knowledge-and-bayesian-thinking.html#reliability-of-scientific-studies"><i class="fa fa-check"></i><b>12.3.2</b> reliability of scientific studies</a></li>
<li class="chapter" data-level="12.3.3" data-path="prior-knowledge-and-bayesian-thinking.html"><a href="prior-knowledge-and-bayesian-thinking.html#discussion-questions-3"><i class="fa fa-check"></i><b>12.3.3</b> discussion questions</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>IV Random models that change with time</b></span></li>
<li class="chapter" data-level="13" data-path="markov-models-with-discrete-states.html"><a href="markov-models-with-discrete-states.html"><i class="fa fa-check"></i><b>13</b> Markov models with discrete states</a>
<ul>
<li class="chapter" data-level="13.1" data-path="markov-models-with-discrete-states.html"><a href="markov-models-with-discrete-states.html#building-markov-models"><i class="fa fa-check"></i><b>13.1</b> Building Markov models</a></li>
<li class="chapter" data-level="13.2" data-path="markov-models-with-discrete-states.html"><a href="markov-models-with-discrete-states.html#markov-property"><i class="fa fa-check"></i><b>13.2</b> Markov property</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="markov-models-with-discrete-states.html"><a href="markov-models-with-discrete-states.html#transition-matrices"><i class="fa fa-check"></i><b>13.2.1</b> transition matrices</a></li>
<li class="chapter" data-level="13.2.2" data-path="markov-models-with-discrete-states.html"><a href="markov-models-with-discrete-states.html#probability-of-a-string-of-states"><i class="fa fa-check"></i><b>13.2.2</b> probability of a string of states</a></li>
<li class="chapter" data-level="13.2.3" data-path="markov-models-with-discrete-states.html"><a href="markov-models-with-discrete-states.html#exercises-27"><i class="fa fa-check"></i><b>13.2.3</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="markov-models-with-discrete-states.html"><a href="markov-models-with-discrete-states.html#markov-models-of-medical-treatment"><i class="fa fa-check"></i><b>13.3</b> Markov models of medical treatment</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="markov-models-with-discrete-states.html"><a href="markov-models-with-discrete-states.html#discussion-questions-4"><i class="fa fa-check"></i><b>13.3.1</b> Discussion questions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="probability-distributions-of-markov-chains.html"><a href="probability-distributions-of-markov-chains.html"><i class="fa fa-check"></i><b>14</b> Probability distributions of Markov chains</a>
<ul>
<li class="chapter" data-level="14.1" data-path="probability-distributions-of-markov-chains.html"><a href="probability-distributions-of-markov-chains.html#probability-distribution-vectors"><i class="fa fa-check"></i><b>14.1</b> Probability distribution vectors</a>
<ul>
<li class="chapter" data-level="14.1.1" data-path="probability-distributions-of-markov-chains.html"><a href="probability-distributions-of-markov-chains.html#markov-chains"><i class="fa fa-check"></i><b>14.1.1</b> Markov chains</a></li>
</ul></li>
<li class="chapter" data-level="14.2" data-path="probability-distributions-of-markov-chains.html"><a href="probability-distributions-of-markov-chains.html#matrix-multiplication"><i class="fa fa-check"></i><b>14.2</b> matrix multiplication</a>
<ul>
<li class="chapter" data-level="14.2.1" data-path="probability-distributions-of-markov-chains.html"><a href="probability-distributions-of-markov-chains.html#exercises-28"><i class="fa fa-check"></i><b>14.2.1</b> Exercises</a></li>
<li class="chapter" data-level="14.2.2" data-path="probability-distributions-of-markov-chains.html"><a href="probability-distributions-of-markov-chains.html#propagation-of-probability-vectors"><i class="fa fa-check"></i><b>14.2.2</b> propagation of probability vectors</a></li>
<li class="chapter" data-level="14.2.3" data-path="probability-distributions-of-markov-chains.html"><a href="probability-distributions-of-markov-chains.html#exercises-29"><i class="fa fa-check"></i><b>14.2.3</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="probability-distributions-of-markov-chains.html"><a href="probability-distributions-of-markov-chains.html#mutations-and-molecular-evolution"><i class="fa fa-check"></i><b>14.3</b> Mutations and molecular evolution</a>
<ul>
<li class="chapter" data-level="14.3.1" data-path="probability-distributions-of-markov-chains.html"><a href="probability-distributions-of-markov-chains.html#discussion-questions-5"><i class="fa fa-check"></i><b>14.3.1</b> Discussion questions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="15" data-path="stationary-distributions-of-markov-chains.html"><a href="stationary-distributions-of-markov-chains.html"><i class="fa fa-check"></i><b>15</b> Stationary distributions of Markov chains</a>
<ul>
<li class="chapter" data-level="15.1" data-path="stationary-distributions-of-markov-chains.html"><a href="stationary-distributions-of-markov-chains.html#history-of-markov-chains"><i class="fa fa-check"></i><b>15.1</b> History of Markov chains</a></li>
<li class="chapter" data-level="15.2" data-path="stationary-distributions-of-markov-chains.html"><a href="stationary-distributions-of-markov-chains.html#stationary-distributions"><i class="fa fa-check"></i><b>15.2</b> Stationary distributions</a>
<ul>
<li class="chapter" data-level="15.2.1" data-path="stationary-distributions-of-markov-chains.html"><a href="stationary-distributions-of-markov-chains.html#exercises-30"><i class="fa fa-check"></i><b>15.2.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="stationary-distributions-of-markov-chains.html"><a href="stationary-distributions-of-markov-chains.html#bioinformatics-and-markov-models"><i class="fa fa-check"></i><b>15.3</b> Bioinformatics and Markov models</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="dynamics-of-markov-models.html"><a href="dynamics-of-markov-models.html"><i class="fa fa-check"></i><b>16</b> Dynamics of Markov models</a>
<ul>
<li class="chapter" data-level="16.1" data-path="dynamics-of-markov-models.html"><a href="dynamics-of-markov-models.html#phylogenetic-trees"><i class="fa fa-check"></i><b>16.1</b> Phylogenetic trees</a></li>
<li class="chapter" data-level="16.2" data-path="dynamics-of-markov-models.html"><a href="dynamics-of-markov-models.html#eigenvalues-and-eigenvectors"><i class="fa fa-check"></i><b>16.2</b> Eigenvalues and eigenvectors</a>
<ul>
<li class="chapter" data-level="16.2.1" data-path="dynamics-of-markov-models.html"><a href="dynamics-of-markov-models.html#basic-linear-algebra"><i class="fa fa-check"></i><b>16.2.1</b> basic linear algebra</a></li>
<li class="chapter" data-level="16.2.2" data-path="dynamics-of-markov-models.html"><a href="dynamics-of-markov-models.html#calculation-of-eigenvalues-on-paper"><i class="fa fa-check"></i><b>16.2.2</b> calculation of eigenvalues on paper</a></li>
<li class="chapter" data-level="16.2.3" data-path="dynamics-of-markov-models.html"><a href="dynamics-of-markov-models.html#calculation-of-eigenvectors-on-paper"><i class="fa fa-check"></i><b>16.2.3</b> calculation of eigenvectors on paper</a></li>
<li class="chapter" data-level="16.2.4" data-path="dynamics-of-markov-models.html"><a href="dynamics-of-markov-models.html#exercises-31"><i class="fa fa-check"></i><b>16.2.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="16.3" data-path="dynamics-of-markov-models.html"><a href="dynamics-of-markov-models.html#eigenvectors-in-r"><i class="fa fa-check"></i><b>16.3</b> Eigenvectors in R</a></li>
<li class="chapter" data-level="16.4" data-path="dynamics-of-markov-models.html"><a href="dynamics-of-markov-models.html#molecular-evolution"><i class="fa fa-check"></i><b>16.4</b> Molecular evolution</a>
<ul>
<li class="chapter" data-level="16.4.1" data-path="dynamics-of-markov-models.html"><a href="dynamics-of-markov-models.html#time-since-divergence"><i class="fa fa-check"></i><b>16.4.1</b> time since divergence</a></li>
<li class="chapter" data-level="16.4.2" data-path="dynamics-of-markov-models.html"><a href="dynamics-of-markov-models.html#phylogenetic-distance"><i class="fa fa-check"></i><b>16.4.2</b> phylogenetic distance</a></li>
<li class="chapter" data-level="16.4.3" data-path="dynamics-of-markov-models.html"><a href="dynamics-of-markov-models.html#kimura-model"><i class="fa fa-check"></i><b>16.4.3</b> Kimura model</a></li>
<li class="chapter" data-level="16.4.4" data-path="dynamics-of-markov-models.html"><a href="dynamics-of-markov-models.html#divergence-of-human-and-chimp-genomes"><i class="fa fa-check"></i><b>16.4.4</b> divergence of human and chimp genomes</a></li>
<li class="chapter" data-level="16.4.5" data-path="dynamics-of-markov-models.html"><a href="dynamics-of-markov-models.html#discussion-questions-6"><i class="fa fa-check"></i><b>16.4.5</b> Discussion questions</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://dkon1.github.io/ql-book/" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Quantifying Life</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="graphical-analysis-of-ordinary-differential-equations" class="section level1" number="7">
<h1><span class="header-section-number">7</span> Graphical analysis of ordinary differential equations</h1>
<blockquote>
<p>I find the great thing in this world is not so much where we stand, as in what direction we are moving.<br />
– Oliver Wendell Holmes, Sr., <em>The Autocrat of the Breakfast Table</em></p>
</blockquote>
<p>We now proceed from linear ODEs to more complicated nonlinear equations. In contrast to linear differential equations, which can be solved in general, nonlinear differential equations may not be solvable even theoretically. Even though the solutions cannot be written down, they exist and can exhibit much more interesting behaviors than the exponential solutions we have seen. When solutions cannot be found on paper, we have two options: 1) use qualitative or graphical tools, such as finding equilibrium points and their stability, to predict the long-term dynamics of the solution; 2) construct numerical solutions that approximate the true solution. In this chapter we concentrate on the qualitative approach to analyzing ODEs, which allows one to predict the behavior of solutions of any autonomous ODE based on the graph of the defining function of the equation. After working through this chapter you will learn to do the following:</p>
<ul>
<li><p>find equilibrium values of an ODE</p></li>
<li><p>analyze the stability of equilibria based on the graph of the defining function</p></li>
<li><p>write down stability conditions analytically</p></li>
<li><p>use graphical techniques to predict the behavior of the solution of a difference equation without solving it</p></li>
<li><p>understand basic compartment epidemiology models</p></li>
</ul>
<div id="building-nonlinear-odes" class="section level2" number="7.1">
<h2><span class="header-section-number">7.1</span> Building nonlinear ODEs</h2>
<p></p>
<p>The simple, linear population growth models we have seen in the last two chapters assume that the per capita birth and death rates are constant, that is, they stay the same regardless of population size. The solutions for these models either grow or decay exponentially, but in reality, populations do not grow without bounds. It is generally true that the larger a population grows, the more scarce the resources, and survival becomes more difficult. For larger populations, this could lead to higher death rates, or lower birth rates, or both.</p>
<p>How can we incorporate this effect into a quantitative model? We will assume there are separate birth and death rates, and that the birth rate declines as the population grows, while the death rate increases. Suppose there are inherent birth rates <span class="math inline">\(b\)</span> and <span class="math inline">\(d\)</span>, and the overall birth and death rates <span class="math inline">\(B\)</span> and <span class="math inline">\(D\)</span> depend linearly on population size <span class="math inline">\(P\)</span>: <span class="math inline">\(B = b - aP\)</span> and <span class="math inline">\(D = d + cP\)</span>.</p>
<p>To model the rate of change of the population, we need to multiply the rates <span class="math inline">\(B\)</span> and <span class="math inline">\(D\)</span> by the population size <span class="math inline">\(P\)</span>, since each individual can reproduce or die. Also, since the death rate <span class="math inline">\(D\)</span> decreases the population, we need to put a negative sign on it. The resulting model is:
<span class="math display">\[ \dot P = BP - DP = [(b-d)-(a+c)P]P \]</span></p>
<p>The parameters of the model, the constants <span class="math inline">\(a,b,c,d\)</span>, have different meanings. Performing  dimensional analysis, we find that <span class="math inline">\(b\)</span> and <span class="math inline">\(d\)</span> have the dimensions of <span class="math inline">\(1/[t]\)</span>, the same as the rate <span class="math inline">\(r\)</span> in the exponential growth model. However, the dimensions of <span class="math inline">\(a\)</span> (and <span class="math inline">\(c\)</span>) must obey the relation: <span class="math inline">\([P]/[t] = [a][P]^2\)</span>, and thus,</p>
<p><span class="math display">\[[a]=[c] = \frac{1}{[t][P]}\]</span></p>
<p>This shows that the constants <span class="math inline">\(a\)</span> and <span class="math inline">\(c\)</span> have to be treated differently than <span class="math inline">\(b\)</span> and <span class="math inline">\(d\)</span>. Let us define the inherent growth rate of the population, to be <span class="math inline">\(r_0=b-d\)</span> (if the death rate is greater than the birth rate, the population will inherently decline). Then let us introduce another constant <span class="math inline">\(K\)</span>, such that <span class="math inline">\((a+c)=r_0/K\)</span>. It should be clear from the dimensional analysis that <span class="math inline">\(K\)</span> has units of <span class="math inline">\(P\)</span>, population size. Now we can write down the logistic equation in the canonical form:
<span class="math display">\[\begin{equation}
\dot P = r\left(1-\frac{P}{K}\right)P
\label{eq:log_cont_model}
\end{equation}\]</span>
This model can be re-written as <span class="math inline">\(\dot P = aP -bP^2\)</span>, so it is clear that there is a <em>linear term</em> (<span class="math inline">\(aP\)</span>) and a <em>nonlinear term</em> (<span class="math inline">\(-bP^2\)</span>). When <span class="math inline">\(P\)</span> is sufficiently small (and positive) the linear term is greater, and the population grows. When <span class="math inline">\(P\)</span> is large enough, the nonlinear term wins and the population declines. </p>
<p>It should be apparent that there are two fixed points, at <span class="math inline">\(P=0\)</span> and at <span class="math inline">\(P=K\)</span>. The first one corresponds to a population with no individuals. On the other hand, <span class="math inline">\(K\)</span> signifies the population at which the negative effect of population size balances out the inherent population growth rate, and is called the  <em>carrying capacity</em> of a population in its environment . We will analyze the qualitative behavior of the solution, without writing it down, in the next section of this chapter.</p>
</div>
<div id="qualitative-analysis-of-odes" class="section level2" number="7.2">
<h2><span class="header-section-number">7.2</span> Qualitative analysis of ODEs</h2>
<p></p>
<p>In this section we will analyze the behavior of solutions of an autonomous ODE without solving it on paper. Generally, ODE models for realistic biological systems are nonlinear, and most nonlinear differential equations cannot be solved analytically. We can make predictions about the behavior, or <em>dynamics</em> of solutions by considering the properties of the  <em>defining function</em>, which is the function on the right-hand-side of a general autonomous ODE:
<span class="math display">\[ \frac{dx}{dt} = f(x)\]</span></p>
<div id="graphical-analysis-of-the-defining-function" class="section level3" number="7.2.1">
<h3><span class="header-section-number">7.2.1</span> graphical analysis of the defining function</h3>
<p>The defining function relates the value of the solution variable <span class="math inline">\(x\)</span> to its rate of change <span class="math inline">\(dx/dt\)</span>. For different values of <span class="math inline">\(x\)</span>, the rate of change of <span class="math inline">\(x(t)\)</span> is different, and it is defined by the function <span class="math inline">\(f(x)\)</span>. There are only three options:</p>
<ul>
<li><p>if <span class="math inline">\(f(x) &gt; 0\)</span>, <span class="math inline">\(x(t)\)</span> is increasing at that value of <span class="math inline">\(x\)</span></p></li>
<li><p>if <span class="math inline">\(f(x) &lt; 0\)</span>, <span class="math inline">\(x(t)\)</span> is decreasing at that value of <span class="math inline">\(x\)</span></p></li>
<li><p>if <span class="math inline">\(f(x) = 0\)</span>, <span class="math inline">\(x(t)\)</span> is not changing that value of <span class="math inline">\(x\)</span></p></li>
</ul>
<p>To determine for which values of <span class="math inline">\(x\)</span> the solution <span class="math inline">\(x(t)\)</span> increases and decreases, it enough to look at the plot of <span class="math inline">\(f(x)\)</span>. On the intervals where the graph of <span class="math inline">\(f(x)\)</span> is above the <span class="math inline">\(x\)</span>-axis <span class="math inline">\(x(t)\)</span> increases, on the intervals where the graph of <span class="math inline">\(f(x)\)</span> is below the <span class="math inline">\(x\)</span>-axis, <span class="math inline">\(x(t)\)</span> decreases. The roots (zeros) of <span class="math inline">\(f(x)\)</span> are special cases, they separate the range of <span class="math inline">\(x\)</span> into the intervals where the solution grows and and where it decreases. This seems exceedingly simple, and it is, but it provides specific information about <span class="math inline">\(x(t)\)</span>, without knowing how to write down its formula.</p>
<p>For an autonomous ODE with one dependent variable, the direction of the rate of change prescribed by the differential equation can be graphically represented by sketching the  <em>flow on the line</em> of the dependent variable. The flow stands for the direction of change at every point, specifically increasing, decreasing, or not changing. The flow is plotted on the horizontal x-axis, so if <span class="math inline">\(x\)</span> is increasing, the flow will be indicated by a rightward arrow, and if it is decreasing, the flow will point to the left. The fixed points separate the regions of increasing (rightward) flow and decreasing (leftward) flow.</p>
<div class="figure" style="text-align: center"><span id="fig:ch7-flow1"></span>
<img src="QuantLife_files/figure-html/ch7-flow1-1.png" alt="a) plot of the defining function of the ODE dx/dt = 4x-100 with direction of flow x(t) indicated with arrows on the x-axis; b) plot of solutions x(t) of the ODE staring with four initial values." width="50%" /><img src="QuantLife_files/figure-html/ch7-flow1-2.png" alt="a) plot of the defining function of the ODE dx/dt = 4x-100 with direction of flow x(t) indicated with arrows on the x-axis; b) plot of solutions x(t) of the ODE staring with four initial values." width="50%" />
<p class="caption">
Figure 7.1: a) plot of the defining function of the ODE dx/dt = 4x-100 with direction of flow x(t) indicated with arrows on the x-axis; b) plot of solutions x(t) of the ODE staring with four initial values.
</p>
</div>
<p><strong>Example.</strong> Consider a linear ODE the likes of which we have solved in section :
<span class="math display">\[\frac{dx}{dt} = 4x -100\]</span>
The defining function is a straight line vs. <span class="math inline">\(x\)</span>, its graph is shown in figure a. Based on this graph, we conclude that the solution decreases when <span class="math inline">\(x&lt;25\)</span> and increases when <span class="math inline">\(x&gt;25\)</span>. Thus we can sketch the solution <span class="math inline">\(x(t)\)</span> over time, without knowing its functional form. The dynamics depends on the initial value: if <span class="math inline">\(x(0)&lt;25\)</span>, the solution will keep decreasing without bound, and go off to negative infinity; if <span class="math inline">\(x(0)&gt;25\)</span>, the solution will keep decreasing without bound, and go off to positive infinity. This is shown by plotting numerical solutions of this ODE for several initial values in figure b. The dotted line shows the location of the special value of 25 which separates the interval of growth from the interval of decline.</p>
<p><strong>Example.</strong> Now let us analyze a nonlinear ODE, specifically the logistic model with the following parameters:
<span class="math display">\[\frac{dP}{dt} =0.3P\left(1-\frac{P}{40}\right)\]</span></p>
<p>The defining function is a downward-facing parabola with two roots at <span class="math inline">\(P=0\)</span> and <span class="math inline">\(P=40\)</span>, as shown in figure a. Between the two roots, the defining function is positive, which means the derivative <span class="math inline">\(dP/dt\)</span> is positive too, so the solution grows on that interval. For <span class="math inline">\(P&lt;0\)</span> and <span class="math inline">\(P&gt;40\)</span>, the solution decreases. Therefore, we can sketch the graphs of the solution <span class="math inline">\(P(t)\)</span> starting with different initial conditions, as show in figure b.</p>
<p>To summarize, the defining function of the ODE determines the rate of change of the solution <span class="math inline">\(x(t)\)</span> depending on the value of <span class="math inline">\(x\)</span>. The graphical approach to finding areas of right and left flow is based on graphing the function <span class="math inline">\(f(x)\)</span>, and dividing the x-axis based on the sign of <span class="math inline">\(f(x)\)</span>. In the areas where <span class="math inline">\(f(x) &gt; 0\)</span>, its graph is above the x-axis, and the flow is to the right; conversely, when <span class="math inline">\(f(x) &lt; 0\)</span>, its graph is below the x-axis, and the flow is to the left. The next subsection puts this approach in a more analytic framework.</p>
<div class="figure" style="text-align: center"><span id="fig:ch7-flow2"></span>
<img src="QuantLife_files/figure-html/ch7-flow2-1.png" alt="a) plot of the defining function of the ODE $dP/dt = 0.3P(1-P/40)$ with direction of flow of P(t) indicated with arrows on the P-axis; b) plot of solutions P(t) of the ODE staring with three initial values" width="50%" /><img src="QuantLife_files/figure-html/ch7-flow2-2.png" alt="a) plot of the defining function of the ODE $dP/dt = 0.3P(1-P/40)$ with direction of flow of P(t) indicated with arrows on the P-axis; b) plot of solutions P(t) of the ODE staring with three initial values" width="50%" />
<p class="caption">
Figure 7.2: a) plot of the defining function of the ODE <span class="math inline">\(dP/dt = 0.3P(1-P/40)\)</span> with direction of flow of P(t) indicated with arrows on the P-axis; b) plot of solutions P(t) of the ODE staring with three initial values
</p>
</div>
</div>
<div id="fixed-points-and-stability" class="section level3" number="7.2.2">
<h3><span class="header-section-number">7.2.2</span> fixed points and stability</h3>
We have seen that the dynamics of solutions of differential equations depend on the initial value of the dependent variable: for some values the solution increases, for others it decreases, and for intermediate values it remains the same. Those special values separating intervals of increase and decrease are called fixed points (or equilibria), and the first step to understanding the dynamics of an ODE is finding its fixed points. A fixed point is a value of the solution at which the dynamical system stays constant, thus, the derivative of the solution must be zero. Here is the formal definition:

<div class="definition">
<span id="def:def-fp" class="definition"><strong>Definition 7.1  </strong></span>For an ordinary differential equation <span class="math inline">\(\dot x = f(x)\)</span>, a point <span class="math inline">\(x^*\)</span> which satisfies <span class="math inline">\(f(x^*)=0\)</span> is called a <em>fixed point</em> or <em>equilibrium</em>, and the solution with the initial condition <span class="math inline">\(x(0)=x^*\)</span> is constant over time <span class="math inline">\(x(t)=x^*\)</span>.
</div>
<p><strong>Example.</strong> The linear equation <span class="math inline">\(\dot x = rx\)</span> has a single fixed point at <span class="math inline">\(x^* = 0\)</span>. For a more interesting example, consider a logistic equation: <span class="math inline">\(\dot x = x - x^2\)</span>. Its fixed points are the solutions of <span class="math inline">\(x - x^2 = 0\)</span>, therefore there two fixed points: <span class="math inline">\(x^* = 0, 1\)</span>. We know that if the solution has either of the fixed points as the initial condition, it will remain at that value for all time.</p>
<p>Locating the fixed points is not sufficient to predict the global behavior of the dynamical system, however. What happens to the solution of a dynamical system if the initial condition is very close to an equilibrium, but not precisely at it? Put another way, what happens if the equilibrium is perturbed? The solution may be attracted to the equilibrium value, that is, it approaches it ever-closer, or else it is not. In the first case, this is called a stable equilibrium, because a small perturbation does not dramatically change the long-term behavior of the solution. In the latter case, the equilibrium is called unstable, and the solution perturbed from the equilibrium never returns. These concepts are formalized in the following definition</p>

<div class="definition">
<span id="def:def-stable" class="definition"><strong>Definition 7.2  </strong></span>A fixed point <span class="math inline">\(x^*\)</span> of an ODE <span class="math inline">\(\dot x = f(x)\)</span> is called a <em>stable</em> fixed point (or sink) if for a sufficiently small number <span class="math inline">\(\epsilon\)</span>, the solution <span class="math inline">\(x(t)\)</span> with the initial condition <span class="math inline">\(x_0 = x^* + \epsilon\)</span> approaches the fixed point <span class="math inline">\(x^*\)</span> as <span class="math inline">\(t \rightarrow \infty\)</span>. If the solution <span class="math inline">\(x(t)\)</span> does not approach <span class="math inline">\(x^*\)</span> for all nonzero <span class="math inline">\(\epsilon\)</span>, the fixed point is called an <em>unstable</em> fixed point (or source).
</div>
<p>To determine whether a fixed point is stable analytically we use the approach called  <em>linearization</em>, which involves replacing the function <span class="math inline">\(f(x)\)</span> with a linear approximation. Let us define <span class="math inline">\(\epsilon(t)\)</span> to be the deviation of the solution <span class="math inline">\(x(t)\)</span> from the fixed point <span class="math inline">\(x^*\)</span>, so we can write <span class="math inline">\(x(t) = x^* + \epsilon(t)\)</span>. Assuming that <span class="math inline">\(\epsilon(t)\)</span> is small, we can write the function <span class="math inline">\(f(x)\)</span> using Taylor’s formula:
<span class="math display">\[ f(x^*+\epsilon(t))= f(x^*)+f&#39;(x^*) \epsilon(t) + ... = f&#39;(x^*) \epsilon(t) + ... \]</span></p>
<p>The term <span class="math inline">\(f(x^*)\)</span> vanished because it is zero by definition  of a fixed point. The ellipsis indicates all the terms of order <span class="math inline">\(\epsilon(t)^2\)</span> and higher, which are very small if <span class="math inline">\(\epsilon(t)\)</span> is small, and thus can be neglected. Thus, we can write the following approximation to the ODE <span class="math inline">\(\dot x = f(x)\)</span> near a fixed point:</p>
<p><span class="math display">\[ \dot x =  \frac{d(x^* + \epsilon(t))}{dt} = \dot \epsilon(t) =  f&#39;(x^*) \epsilon(t)\]</span></p>
<p>Thus we replaced the complicated nonlinear ODE near a fixed point with a linear equation, which approximates the dynamics of the deviation <span class="math inline">\(\epsilon(t)\)</span> near the fixed point <span class="math inline">\(x^*\)</span>; note that the derivative <span class="math inline">\(f&#39;(x^*)\)</span> is a constant for any given fixed point. In section  we classified the behavior of solutions for the general linear ODE <span class="math inline">\(\dot x = rx\)</span>, and now we apply this classification to the behavior of the deviation <span class="math inline">\(\epsilon(t)\)</span>. If the multiple <span class="math inline">\(f&#39;(x^*)\)</span> is positive, the deviation <span class="math inline">\(\epsilon(t)\)</span> is growing, the solution is diverging away from the fixed point, and thus the fixed point is unstable. If the multiple <span class="math inline">\(f&#39;(x^*)\)</span> is negative, the deviation <span class="math inline">\(\epsilon(t)\)</span> is decaying, the solution is converging to the fixed point, and thus the fixed point is stable. Finally, there is the borderline case of <span class="math inline">\(f&#39;(x^*) = 0\)</span> which is inconclusive, and the fixed point may be either stable or unstable. The  derivative stability analysis is summarized in the following:</p>
<ul>
<li><span class="math inline">\(f&#39;(x^*) &gt; 0\)</span>: the slope of <span class="math inline">\(f(x)\)</span> at the fixed point is positive, then the fixed point is .</li>
<li><span class="math inline">\(f&#39;(x^*) &lt; 0\)</span>: the slope of <span class="math inline">\(f(x)\)</span> at the fixed point is negative, then the fixed point is .</li>
<li><span class="math inline">\(f&#39;(x^*) = 0\)</span>: stability cannot be determined from the derivative.</li>
</ul>
<p>Therefore, knowing the derivative or the slope of the defining function at the fixed point is enough to know its stability. If the derivative has the discourtesy of being zero, the situation is tricky, because then higher order terms that we neglected make the difference. We will mostly avoid such borderline cases, but they are important in some applications .</p>
<p><strong>A word of caution:</strong> The derivative of the defining function <span class="math inline">\(f&#39;(x)\)</span> is not the second derivative of the solution <span class="math inline">\(x(t)\)</span>. This is a common mistake, because the function <span class="math inline">\(f(x)\)</span> is equal to the time derivative of <span class="math inline">\(x(t)\)</span>. However, the derivative <span class="math inline">\(f&#39;(x)\)</span> is not with respect to time, it is with respect to x, the dependent variable. In other words, it reflects the slope of the graph of the defining function <span class="math inline">\(f(x)\)</span>, not the curvature of the graph of the solution <span class="math inline">\(x(t)\)</span>.</p>
<p>To summarize, here is an outline of the steps for analyzing the behavior of solutions of an autonomous one-variable ODE. These tasks can be accomplished either by plotting the defining function <span class="math inline">\(f(x)\)</span> and finding the fixed points and their stability based on the plot, or by solving for the fixed points on paper, then finding the derivative <span class="math inline">\(f&#39;(x)\)</span> and plugging in the values of the fixed points to determine their stability. Either approach is valid, but the analytic methods are necessary when dealing with models that have unknown parameter values, which makes it impossible to represent the defining function in a plot.</p>
</div>
<div id="outline-of-qualitative-analysis-of-an-ode" class="section level3" number="7.2.3">
<h3><span class="header-section-number">7.2.3</span> Outline of qualitative analysis of an ODE</h3>
<ul>
<li><p>find the fixed points by setting the defining function <span class="math inline">\(f(x)=0\)</span> and solving for values of <span class="math inline">\(x^*\)</span></p></li>
<li><p>divide the domain of <span class="math inline">\(x\)</span> into intervals separated by fixed points <span class="math inline">\(x^*\)</span></p></li>
<li><p>determine on which interval(s) the solution <span class="math inline">\(x(t)\)</span> is increasing and on which it is decreasing</p></li>
<li><p>use derivative stability analysis (graphically or analytically) to determine which fixed points are stable</p></li>
<li><p>sketch the solutions <span class="math inline">\(x(t)\)</span> starting at different initial values, based on the stability analysis and whether the solution is increasing or decreasing in a particular interval</p></li>
</ul>
<p><strong>Example: linear model.</strong> Consider the linear ODE that we analyzed above <span class="math inline">\(dx/dt = 4x -100\)</span>. Let us go through the steps of qualitative analysis:</p>
<ul>
<li><p>find the fixed points by setting the defining function to 0: <span class="math inline">\(0 = 4x -100\)</span>, so there is only one fixed point <span class="math inline">\(x^* = 25\)</span></p></li>
<li><p>divide the domain of <span class="math inline">\(x\)</span> into intervals separated by fixed points <span class="math inline">\(x^*\)</span>: the intervals are <span class="math inline">\(x&lt;25\)</span> and <span class="math inline">\(x&gt;25\)</span></p></li>
<li><p>the solution is decreasing on the interval <span class="math inline">\(x&lt;25\)</span> because <span class="math inline">\(f(x)&lt;0\)</span> there, and the solution is increasing on the interval <span class="math inline">\(x&gt;25\)</span> because <span class="math inline">\(f(x)&gt;0\)</span></p></li>
<li><p>the derivative <span class="math inline">\(f&#39;(x)\)</span> at the fixed point is 4, so the fixed point is <em>unstable</em></p></li>
<li><p>solutions <span class="math inline">\(x(t)\)</span> starting at different initial values are shown in figure b and they behave as follows: solutions with initial values below <span class="math inline">\(x^*=25\)</span> decreasing, and those with initial values above <span class="math inline">\(x^*=25\)</span> increasing.</p></li>
</ul>
<p>** Example: logistic model.**  Consider the logistic model from the previous subsection, <span class="math inline">\(dP/dt =0.3P(1-P/40)\)</span>. We have analyzed the stability of the two fixed points using the plot in figure , and saw that the flow takes the solution away from <span class="math inline">\(P=0\)</span>, and toward <span class="math inline">\(P=K\)</span>, thus the first fixed point is unstable, while the second is stable. Let us repeat the analysis using analytic tools:</p>
<ul>
<li><p>find the fixed points by setting the defining function to 0: <span class="math inline">\(0 = 0.3P(1-P/40)\)</span>. The two solutions are <span class="math inline">\(P^*=0\)</span> and <span class="math inline">\(P^*=40\)</span>.</p></li>
<li><p>divide the domain of <span class="math inline">\(P\)</span> into intervals separated by fixed points <span class="math inline">\(P^*\)</span>: the intervals are <span class="math inline">\(P&lt;0\)</span>; <span class="math inline">\(0&lt;P&lt;40\)</span>; and <span class="math inline">\(P&gt;40\)</span></p></li>
<li><p>the solution is decreasing on the interval <span class="math inline">\(P&lt;0\)</span> because <span class="math inline">\(f(P)&lt;0\)</span> there, the solution is increasing on the interval <span class="math inline">\(0&lt;P&lt;40\)</span> because <span class="math inline">\(f(P)&gt;0\)</span>, and the solution is decreasing for <span class="math inline">\(P&gt;40\)</span> because <span class="math inline">\(f(P)&lt;0\)</span> there</p></li>
<li><p>the derivative is <span class="math inline">\(f&#39;(P)=0.3-0.3P/20\)</span>; since <span class="math inline">\(f&#39;(0)=0.3 &gt; 0\)</span>, the fixed point is <em>unstable</em>; since <span class="math inline">\(P&#39;(40)=-0.3&lt;0\)</span>, the fixed point is <em>stable</em></p></li>
<li><p>solutions <span class="math inline">\(P(t)\)</span> starting at different initial values are shown in figure b and they behave as follows: solutions with initial values below <span class="math inline">\(P^*=0\)</span> decreasing, those with initial values between 0 and 40 are increasing and asymptotically approaching 40, and those with initial values above 40 decreasing and asymptotically approaching 40.</p></li>
</ul>
<p>This can be done more generally using the derivative test: taking the derivative of the function on the right-hand-side (with respect to <span class="math inline">\(P\)</span>), we get <span class="math inline">\(f&#39;(P) = r(1-2\frac{P}{K})\)</span>. Assuming <span class="math inline">\(r&gt;0\)</span> (the population is viable), <span class="math inline">\(f&#39;(0)= r\)</span> is positive, and the fixed point is therefore unstable. This makes biological sense, since we assumed positive inherent population growth, so given a few individuals, it will increase in size. On the other hand, <span class="math inline">\(P&#39;(K) = r(1-2) = -r\)</span>, so this fixed point is stable. Thus, according to the logistic model, a population with a positive inherent growth rate will not grow unchecked, like in the exponential model, but will increase until it reaches its carrying capacity, at which it will stay (if all parameters remain constant).</p>
<p><strong>Example: semi-stable fixed point.</strong> Consider the ODE <span class="math inline">\(dx/dt = -x^3 + x^2\)</span>, whose defining function is plotted in figure a, showing two fixed points at <span class="math inline">\(x = 0, 1\)</span>.</p>
<ul>
<li><p>find the fixed points by setting the defining function to 0: <span class="math inline">\(0 = -x^3 + x^2\)</span>. The two fixed points are <span class="math inline">\(x^*=0\)</span> and <span class="math inline">\(x^*=1\)</span>.</p></li>
<li><p>divide the domain of <span class="math inline">\(x\)</span> into intervals separated by fixed points <span class="math inline">\(x^*\)</span>: the intervals are <span class="math inline">\(x&lt;0\)</span>; <span class="math inline">\(0&lt;x&lt;1\)</span>; and <span class="math inline">\(x&gt;1\)</span></p></li>
<li><p>the solution is increasing on the interval <span class="math inline">\(x&lt;0\)</span> because <span class="math inline">\(f(x)&gt;0\)</span> there, the solution is increasing on the interval <span class="math inline">\(0&lt;x&lt;1\)</span> because <span class="math inline">\(f(x)&gt;0\)</span>, and the solution is decreasing for <span class="math inline">\(x&gt;1\)</span> because <span class="math inline">\(f(x)&lt;0\)</span> there</p></li>
<li><p>the derivative is <span class="math inline">\(f&#39;(x)=-3x^2+2x\)</span>; since <span class="math inline">\(f&#39;(0)=0\)</span>, the fixed point is <em>undetermined</em>; since <span class="math inline">\(f&#39;(1)=-1&lt;0\)</span>, the fixed point is <em>stable</em>.</p></li>
<li><p>the solutions <span class="math inline">\(x(t)\)</span> starting at different initial values are shown in figure b, and they behave as follows: solutions with initial values below 0 are increasing and asymptotically approaching 0, those with initial values between 0 and 1 are increasing and asymptotically approaching 1, and those with initial values above 1 are decreasing and asymptotically approaching 1.</p></li>
</ul>
<p>This example shows how graphical analysis can help when derivative analysis is undetermined. The red arrows on the x-axis of figure  show the direction of the flow in the three different regions separated by the fixed points. Flow is to the right for <span class="math inline">\(x&lt;1\)</span>, to the left for for <span class="math inline">\(x&gt;1\)</span>; it is clear that the arrows approach the fixed point from both sides, and thus the fixed point is stable, as the negative slope of <span class="math inline">\(f(x)\)</span> at <span class="math inline">\(x=1\)</span> indicates. One the other hand, the fixed point at <span class="math inline">\(x=0\)</span> presents a more complicated situation: the slope of <span class="math inline">\(f(x)\)</span> is zero, and the flow is rightward on both sides of the fixed point. This type of fixed point is sometimes called <em>semi-stable</em>, because it is stable when approached from one side, and unstable when approached from the other.</p>
<div class="figure" style="text-align: center"><span id="fig:ch7-flow3"></span>
<img src="QuantLife_files/figure-html/ch7-flow3-1.png" alt="a) plot of the defining function of the ODE $dx/dt = -x^3 + x^2$ with direction of flow of x(t) indicated with arrows on the x-axis; b) plot of solutions x(t) of the ODE staring with three initial values" width="50%" /><img src="QuantLife_files/figure-html/ch7-flow3-2.png" alt="a) plot of the defining function of the ODE $dx/dt = -x^3 + x^2$ with direction of flow of x(t) indicated with arrows on the x-axis; b) plot of solutions x(t) of the ODE staring with three initial values" width="50%" />
<p class="caption">
Figure 7.3: a) plot of the defining function of the ODE <span class="math inline">\(dx/dt = -x^3 + x^2\)</span> with direction of flow of x(t) indicated with arrows on the x-axis; b) plot of solutions x(t) of the ODE staring with three initial values
</p>
</div>
</div>
<div id="exercises-19" class="section level3" number="7.2.4">
<h3><span class="header-section-number">7.2.4</span> Exercises</h3>
<p>For the following differential equations: a) plot the defining function over the indicated range (use any computational tools you wish) to determine the intervals on which the dependent variable is increasing and decreasing; b) find the equilibria c) determine the stability of each equilibrium; d) based on your analysis in parts a-c, sketch (by hand) plots of the solutions with the specified initial values.</p>
<ol style="list-style-type: decimal">
<li><p><span class="math display">\[ \frac{dC}{dt} = -0.2C + 60; \; C \in (0,500); \; C(0) = 200; \; C(0) = 400 \]</span></p></li>
<li><p><span class="math display">\[ \frac{dP}{dt} = 0.01P(800-P) - 0.5P; \; P \in (-1, 1000); \; P(0) = 100; \; P(0) = 800\]</span></p></li>
<li><p><span class="math display">\[ \frac{dR}{dt} = R(80-R) - 1200; \; R \in (-1, 100); \; R(0) = 10; \; R(0) = 80\]</span></p></li>
<li><p><span class="math display">\[ \frac{dI}{dt} = 0.1I(1-I) - 0.03I; \;  I \in (-0.1, 1.1); \; I(0) = 0.2; \; I(0) = 0.9 \]</span></p></li>
<li><p><span class="math display">\[  \frac{dR}{dt} = \frac{R}{1+R}-0.1R; \; R \in (-0.1, 10); \; R(0) = 20; \; R(0) = 0 \]</span></p></li>
<li><p><span class="math display">\[  \frac{dP}{dt} =  0.02P(P-100)(1200-P) \; P \in (-0.1, 1200); \; P(0) = 20; \; P(0) = 1000 \]</span></p></li>
<li><p><span class="math display">\[  \frac{dY}{dt} =  0.01Y(Y-100)(Y-200) \; Y \in (-0.1, 300); \; Y(0) = 20; \; Y(0) = 250 \]</span></p></li>
<li><p>(harder) The logistic function was defined in chapter 2, equation 2.4. Verify that the logistic function with independent variable <span class="math inline">\(t\)</span> solves the logistic ODE in equation  and relate the parameters in the function to the parameters <span class="math inline">\(r\)</span> and <span class="math inline">\(K\)</span> in the ODE.</p></li>
</ol>
</div>
</div>
<div id="functions-in-r" class="section level2" number="7.3">
<h2><span class="header-section-number">7.3</span> Functions in R</h2>
<p>Like most programming languages, R allows one to define and use structures called functions. Some are already written and loaded into the R distribution, for example, the function <code>mean()</code> we use to compute the mean of a vector variable, while others can be defined by users. Functions are discrete chunks of code that can be <em>called</em> from the outside to perform some task. The function receives inputs from the call and returns the result back. Here is the general structure of a function in R:</p>
<div class="sourceCode" id="cb213"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb213-1"><a href="graphical-analysis-of-ordinary-differential-equations.html#cb213-1" aria-hidden="true"></a>myfunction &lt;-<span class="st"> </span><span class="cf">function</span>(arg1, arg2, ...) {</span>
<span id="cb213-2"><a href="graphical-analysis-of-ordinary-differential-equations.html#cb213-2" aria-hidden="true"></a>    statements</span>
<span id="cb213-3"><a href="graphical-analysis-of-ordinary-differential-equations.html#cb213-3" aria-hidden="true"></a>    <span class="kw">return</span>(answer)</span>
<span id="cb213-4"><a href="graphical-analysis-of-ordinary-differential-equations.html#cb213-4" aria-hidden="true"></a>}</span></code></pre></div>
<p>A function is a piece of code that is <strong>defined</strong> separately and can be <strong>called</strong> by other pieces of code. The main purpose is to create a “black box” that does a specific job and can be used repeatedly just by calling the function (invoking its name), rather than copying the code repeatedly.</p>
<p>A function generally has input variables (although sometimes there are none) and returns an output using the <code>return()</code> statement. It is important to distinguish between the <em>inside</em> of the function - the code between the curly braces in the function definition - and the <em>outside</em>, that is everything else. The inputs are <em>passed</em> to the function in the call (through the parentheses) and then used inside the function to do its business and produce an output, which is then <em>returned</em> back to the place in the code where the function was called.</p>
<div id="defining-a-function" class="section level3" number="7.3.1">
<h3><span class="header-section-number">7.3.1</span> defining a function</h3>
<p>Here is an example of a function definition, with input variables N and r. Between the curly braces is the <em>body of the function</em>, which in this case multiplies the two input variables and then returns them.</p>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb214-1"><a href="graphical-analysis-of-ordinary-differential-equations.html#cb214-1" aria-hidden="true"></a>my_funk &lt;-<span class="st"> </span><span class="cf">function</span>(N,r){ </span>
<span id="cb214-2"><a href="graphical-analysis-of-ordinary-differential-equations.html#cb214-2" aria-hidden="true"></a>  ans &lt;-<span class="st"> </span>r<span class="op">*</span>N <span class="co"># updating function f(N)</span></span>
<span id="cb214-3"><a href="graphical-analysis-of-ordinary-differential-equations.html#cb214-3" aria-hidden="true"></a>  <span class="kw">return</span>(ans)</span>
<span id="cb214-4"><a href="graphical-analysis-of-ordinary-differential-equations.html#cb214-4" aria-hidden="true"></a>}</span></code></pre></div>
<p>Note that after running the code chunk above, you should see the name <code>my_funk</code> in your environment (under Functions). This means this function is defined in memory and ready to be called.</p>
</div>
<div id="calling-a-function" class="section level3" number="7.3.2">
<h3><span class="header-section-number">7.3.2</span> calling a function</h3>
<p>After a function is defined, it is ready to be called (executed) by invoking its name and giving the correct number of inputs. Here’s an example of a function call:</p>
<div class="sourceCode" id="cb215"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb215-1"><a href="graphical-analysis-of-ordinary-differential-equations.html#cb215-1" aria-hidden="true"></a>a &lt;-<span class="st"> </span><span class="dv">30</span></span>
<span id="cb215-2"><a href="graphical-analysis-of-ordinary-differential-equations.html#cb215-2" aria-hidden="true"></a>y &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">:</span><span class="dv">10</span></span>
<span id="cb215-3"><a href="graphical-analysis-of-ordinary-differential-equations.html#cb215-3" aria-hidden="true"></a><span class="kw">print</span>(<span class="kw">my_funk</span>(y, a))</span></code></pre></div>
<pre><code>##  [1]  30  60  90 120 150 180 210 240 270 300</code></pre>
<p>Notice that the variable names in the fuction call do not have to be same as what they are called within the function. IMPORTANT: a function uses the order of variables in the function call, called <em>external variables</em> (<code>y</code>, <code>a</code>) to assign their names within the function, called <em>internal variables</em> (<code>N</code>, <code>r</code>). (There is a way to specify which input belongs to which internal variable, e.g. <code>plot(x=time, y=sol)</code> and in that case the order is not important.)</p>
</div>
<div id="using-a-function-to-solve-a-difference-equation" class="section level3" number="7.3.3">
<h3><span class="header-section-number">7.3.3</span> using a function to solve a difference equation</h3>
<p>We have solved discrete-time dynamic models (difference equations) using for loops. You can use a function to calculate the next value of the solution, by passing the current value and any parameters as inputs to the function, as you can see in the code chunk below:</p>
<div class="sourceCode" id="cb217"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb217-1"><a href="graphical-analysis-of-ordinary-differential-equations.html#cb217-1" aria-hidden="true"></a>numsteps&lt;-<span class="dv">30</span> <span class="co"># set number of steps</span></span>
<span id="cb217-2"><a href="graphical-analysis-of-ordinary-differential-equations.html#cb217-2" aria-hidden="true"></a>sol &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="dv">0</span>,numsteps<span class="op">+</span><span class="dv">1</span>) <span class="co"># pre-allocate sol1</span></span>
<span id="cb217-3"><a href="graphical-analysis-of-ordinary-differential-equations.html#cb217-3" aria-hidden="true"></a>sol[<span class="dv">1</span>] &lt;-<span class="st"> </span><span class="dv">100</span> <span class="co"># set initial value</span></span>
<span id="cb217-4"><a href="graphical-analysis-of-ordinary-differential-equations.html#cb217-4" aria-hidden="true"></a>r &lt;-<span class="st"> </span><span class="dv">2</span> <span class="co"># define the multiplicative constant</span></span>
<span id="cb217-5"><a href="graphical-analysis-of-ordinary-differential-equations.html#cb217-5" aria-hidden="true"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span>numsteps) { <span class="co"># repeat for numsteps</span></span>
<span id="cb217-6"><a href="graphical-analysis-of-ordinary-differential-equations.html#cb217-6" aria-hidden="true"></a>  sol[i<span class="op">+</span><span class="dv">1</span>] &lt;-<span class="st"> </span><span class="kw">my_funk</span>(sol[i], r) <span class="co"># calculate the next value</span></span>
<span id="cb217-7"><a href="graphical-analysis-of-ordinary-differential-equations.html#cb217-7" aria-hidden="true"></a>}</span>
<span id="cb217-8"><a href="graphical-analysis-of-ordinary-differential-equations.html#cb217-8" aria-hidden="true"></a>time &lt;-<span class="st"> </span><span class="dv">0</span><span class="op">:</span>numsteps <span class="co"># define time vector</span></span>
<span id="cb217-9"><a href="graphical-analysis-of-ordinary-differential-equations.html#cb217-9" aria-hidden="true"></a><span class="kw">plot</span>(time,sol,<span class="dt">t=</span><span class="st">&#39;b&#39;</span>,<span class="dt">xlab=</span><span class="st">&#39;time&#39;</span>,<span class="dt">ylab=</span><span class="st">&#39;solution&#39;</span>,<span class="dt">lwd=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="QuantLife_files/figure-html/unnamed-chunk-126-1.png" width="672" /></p>
</div>
<div id="exercises-20" class="section level3" number="7.3.4">
<h3><span class="header-section-number">7.3.4</span> Exercises</h3>
<ol style="list-style-type: decimal">
<li>Write a function that takes the input variable and multiplies it by 1.03, like the mathematical function <span class="math inline">\(f(x) = 1.03x\)</span>.</li>
</ol>
<div class="sourceCode" id="cb218"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb218-1"><a href="graphical-analysis-of-ordinary-differential-equations.html#cb218-1" aria-hidden="true"></a><span class="co"># YOUR CODE HERE</span></span></code></pre></div>
<ol start="2" style="list-style-type: decimal">
<li>Use the function to take a variable and multiply it by 1.03, replacing the old value of the variable. If the initial value is 5, the new value should be 5.15.</li>
</ol>
<div class="sourceCode" id="cb219"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb219-1"><a href="graphical-analysis-of-ordinary-differential-equations.html#cb219-1" aria-hidden="true"></a><span class="co"># YOUR CODE HERE</span></span></code></pre></div>
<ol start="3" style="list-style-type: decimal">
<li>Write a script to take a variable and multiply it by 1.03 one hundred times, replacing the old value of the variable <strong>using a for loop and the function you created</strong>. Starting with the initial value is 5, the script should return the value 96.093.</li>
</ol>
<div class="sourceCode" id="cb220"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb220-1"><a href="graphical-analysis-of-ordinary-differential-equations.html#cb220-1" aria-hidden="true"></a><span class="co"># YOUR CODE HERE</span></span></code></pre></div>
<ol start="4" style="list-style-type: decimal">
<li>Modify the script above to save all the intermediate values into a vector, and plot a graph of this vector vs. the iteration step (from 1 to 101). Hint: this is exactly like the example code above.</li>
</ol>
<div class="sourceCode" id="cb221"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb221-1"><a href="graphical-analysis-of-ordinary-differential-equations.html#cb221-1" aria-hidden="true"></a><span class="co"># YOUR CODE HERE</span></span></code></pre></div>
</div>
</div>
<div id="modeling-the-spread-of-infectious-disease-spread" class="section level2" number="7.4">
<h2><span class="header-section-number">7.4</span> Modeling the spread of infectious disease spread</h2>
<p></p>
<p>The field of <em>epidemiology</em> studies the distribution of disease and health states in populations. Epidemiologists describe and model these issues with the goal of helping public health workers devise interventions to improve the overall health outcomes on a large scale. One particular topic of interest is the the spread of infectious disease and how best tor respond to it.. Because epidemiology is concerned with large numbers of people, the models used in the field do not address the details of an individual disease history. One approach to modeling this is to put people into categories, such as <em>susceptible</em> (those who can be infected but are not), <em>infectious</em> (those who are infected and can spread the disease), and <em>recovered</em> (those who cannot be infected or spread disease). This type of models is called a  <em>compartment model</em> and they are they commonly used to represent infectious disease on a population level both for deterministic models (e.g. ODEs) and stochastic models (e.g. Markov models). Dividing people into categories involves the assumption that everyone in a particular category behaves in the same manner: for instance, all susceptible people are infected with the same rate and all infected people recover with the same rate.</p>
<p>Let us construct an ODE to describe a two-compartment epidemiology model. There are two dependent variables to be tracked: the number of susceptible (<span class="math inline">\(S\)</span>) and infected (<span class="math inline">\(I\)</span>) individuals in the population. The susceptible individuals can get infected, while the infected ones can recover and become susceptible again. The implicit assumption is that there is no immunity, and recovered individuals can get infected with the same ease as those who were never infected. There are some human diseases for which this is true, for instance the common cold or gonorrhea. Transitions between the different classes of individuals can be summarized by the following scheme:
<span class="math display">\[ S + I \xrightarrow{\beta} I \xrightarrow{\gamma} S \]</span>
Here <span class="math inline">\(\beta\)</span> is the individual rate of infection, also known as the transmission rate, and <span class="math inline">\(\gamma\)</span> is the individual rate of recovery. There is an important distinction between the processes of infection and recovery: the former requires an infected individual and a susceptible individual, while the latter needs only an infected individual. Therefore, it is reasonable to suppose that the rate of growth of infected individuals is the product of the individual transmission rate <span class="math inline">\(\beta\)</span> and the product of the number of infected and susceptible individuals. The overall rate of recovery is the individual recovery rate <span class="math inline">\(\gamma\)</span> multiplied by the number of the infected. This leads to the following two differential equations:
<span class="math display">\[\begin{eqnarray*}
\dot S &amp;=&amp; -\beta IS + \gamma I \\
\dot I &amp; = &amp;\beta I S - \gamma I
\end{eqnarray*}\]</span>
Note that, as in the chemical kinetics models, the two equations add up to zero on the right hand side, leading to the conclusion that <span class="math inline">\(\dot S + \dot I = 0\)</span>. Therefore, the total number of people is a conserved quantity <span class="math inline">\(N\)</span>, which does not change. This makes sense since we did not consider any births or deaths in the ODE model, only transitions between susceptible and infected individuals.</p>
<p>We can use the conserved quantity <span class="math inline">\(N\)</span> to reduce the two equations to one, by the substitution of <span class="math inline">\(S = N -I\)</span>:
<span class="math display">\[  \dot I  =  \beta I (N - I) - \gamma I \]</span>
This model may be analyzed using qualitative methods that were developed in this chapter, allowing prediction of the dynamics of the fraction of infected for different transmission and recovery rates. First, let us find the fixed points of the differential equation. Setting the equation to zero, we find:
<span class="math display">\[ 0  =  \beta I (N - I) - \gamma I \Rightarrow I^* = 0; \; I^* =  N - \gamma/\beta \]</span>
This means that there are two equilibrium levels of infection: either nobody is infected (<span class="math inline">\(I^* = 0\)</span>) or there is some persistent number of infected individuals ($ I^* = N - /$). Notice that the second fixed point is only biologically relevant if $N &gt; /$.</p>
<p>Use the derivative test to check for stability. First, find the general expression for derivative of the defining function: $f’(I) = -2 I + N - $.
\begin{figure}[htbp] % figure placement: here, top, bottom, or page</p>
<div class="figure" style="text-align: center"><span id="fig:ch7-flow-sis1"></span>
<img src="QuantLife_files/figure-html/ch7-flow-sis1-1.png" alt="Graphical analysis of the SIS model with $I$ representing the fraction of infected individuals (N=1) and beta=0.5 and gamma = 0.2; a) plot showing the flow of the solutions on the I-axis, with a stable equilibrium at 0.6 and an unstable equilibrium at 0; b) three solutions of the model starting at three different initial values all converge to the same fraction of infected." width="50%" /><img src="QuantLife_files/figure-html/ch7-flow-sis1-2.png" alt="Graphical analysis of the SIS model with $I$ representing the fraction of infected individuals (N=1) and beta=0.5 and gamma = 0.2; a) plot showing the flow of the solutions on the I-axis, with a stable equilibrium at 0.6 and an unstable equilibrium at 0; b) three solutions of the model starting at three different initial values all converge to the same fraction of infected." width="50%" />
<p class="caption">
Figure 7.4: Graphical analysis of the SIS model with <span class="math inline">\(I\)</span> representing the fraction of infected individuals (N=1) and beta=0.5 and gamma = 0.2; a) plot showing the flow of the solutions on the I-axis, with a stable equilibrium at 0.6 and an unstable equilibrium at 0; b) three solutions of the model starting at three different initial values all converge to the same fraction of infected.
</p>
</div>
<div class="figure" style="text-align: center"><span id="fig:ch7-flow-sis2"></span>
<img src="QuantLife_files/figure-html/ch7-flow-sis2-1.png" alt="Graphical analysis of the SIS model with I representing the fraction of infected individuals (N=1) and beta=0.2 and gamma = 0.3; a) plot showing the flow of the solutions on the I-axis, with a stable equilibrium at 0 and an unstable equilibrium at -0.5; b) three solutions of the model starting at three different initial values all converge to 0 infected." width="50%" /><img src="QuantLife_files/figure-html/ch7-flow-sis2-2.png" alt="Graphical analysis of the SIS model with I representing the fraction of infected individuals (N=1) and beta=0.2 and gamma = 0.3; a) plot showing the flow of the solutions on the I-axis, with a stable equilibrium at 0 and an unstable equilibrium at -0.5; b) three solutions of the model starting at three different initial values all converge to 0 infected." width="50%" />
<p class="caption">
Figure 7.5: Graphical analysis of the SIS model with I representing the fraction of infected individuals (N=1) and beta=0.2 and gamma = 0.3; a) plot showing the flow of the solutions on the I-axis, with a stable equilibrium at 0 and an unstable equilibrium at -0.5; b) three solutions of the model starting at three different initial values all converge to 0 infected.
</p>
</div>
<p>The stability of the fixed point <span class="math inline">\(I^* = 0\)</span> is found by plugging in this value into the derivative formula: $f’(0) = N - $. We learned in section  that a fixed point is stable if the derivative of the defining function is negative. Therefore, <span class="math inline">\(I^* = 0\)</span> is stable if <span class="math inline">\(\gamma - \beta N &gt; 0\)</span>, and unstable otherwise. This gives us a  <em>stability condition</em> on the values of the biological parameters. If the recovery rate <span class="math inline">\(\gamma\)</span> is greater than the rate of infection for the population (the transmission rate multiplied by the population size) <span class="math inline">\(\beta N\)</span>, then the no-infection equilibrium is stable. This predicts that the infection dies out if the recovery rate is faster than the rate of infection, which makes biological sense.</p>
<p>Similarly, we find the stability of the second fixed point <span class="math inline">\(I^* = N - \gamma/\beta\)</span> by substituting its value into the derivative, to obtain <span class="math inline">\(f&#39;(N - \gamma/\beta) = \gamma - \beta N\)</span>. By the same logic, as above, this fixed point is stable if <span class="math inline">\(\gamma - \beta N &lt; 0\)</span>, or if <span class="math inline">\(\gamma &lt; \beta N\)</span>. This is a complementary condition for the fixed point at 0, that is, only one fixed point can be stable for any given parameter values. In the biological interpretation, if the transmission rate <span class="math inline">\(\beta N\)</span> is greater than the recovery rate <span class="math inline">\(\gamma\)</span>, then the epidemic will persist.</p>
<p>We can use our graphical analysis skills to illustrate the situation. Consider a situation in which <span class="math inline">\(\gamma &lt; \beta N\)</span>. As predicted by stability analysis, the zero infection equilibrium should be unstable, and the equilibrium at <span class="math inline">\(N - \gamma/\beta\)</span> should be stable. In order to plot the function $f(I) = I (N - I) - I $, we choose the specific parameter values <span class="math inline">\(N=1\)</span>, <span class="math inline">\(\gamma = 0.1\)</span> and <span class="math inline">\(\beta = 0.2\)</span>; setting <span class="math inline">\(N=1\)</span> means <span class="math inline">\(S\)</span> and <span class="math inline">\(I\)</span> represent the fraction of the population in the susceptible and infected categories. Figure a shows the direction of the flow on the <span class="math inline">\(I\)</span>-axis prescribed by the defining function <span class="math inline">\(f(I)\)</span> with red arrows. It is clear that solutions approach the fixed point at <span class="math inline">\(N - \gamma/\beta\)</span> from both directions, which make it a stable fixed point, while diverging from <span class="math inline">\(I=0\)</span>, as shown in figure b.</p>
<p>On the other hand, if <span class="math inline">\(\gamma &gt; \beta N\)</span>, stability analysis predicts that the no-infection equilibrium (<span class="math inline">\(I=0\)</span>) is stable. Figure a shows the plot of the defining function for the parameter values <span class="math inline">\(N=1\)</span>, <span class="math inline">\(\gamma = 0.3\)</span> and <span class="math inline">\(\beta = 0.2\)</span>. The flow on the <span class="math inline">\(I\)</span>-axis is toward the zero equilibrium, therefore it is stable. Note that the second equilibrium at <span class="math inline">\(I^* = N - \gamma/\beta\)</span> is negative, and thus has no biological significance. The solutions, if the initial value is positive, all approach 0, so the infection inevitably dies out.</p>
<p>Mathematical modeling of epidemiology has been a success story in the last few decades. Public health workers routinely estimate the parameter called the  <em>basic reproductive number</em> <span class="math inline">\(R_0\)</span> defined to be the average number of new infections caused by a single infected individual in a susceptible population. This number comes out of our analysis above, where we found <span class="math inline">\(R_0 = N \beta/\gamma\)</span> to determine whether or not an epidemic persisted . This number is critical in more sophisticated models of epidemiology.</p>
<p>Mathematical models are used to predict the time course of an epidemic, called the  <em>epidemic curve</em> and then advise on the public health interventions that can reduce the number of affected individuals. In reality, most epidemic curves have the shape similar to the data from the Ebola virus epidemic in figure . Most such curves show an initial increase in infections, peaking, and the declining to low levels, which is fundamentally different than the solution curves we obtained from the two-compartment model. To describe dynamics of this nature, models with more than two variables are needed, such as classic three-compartment SIR models (susceptible-infected-recovered) models and their modifications . Being able to predict the future of an epidemic based on <span class="math inline">\(R_0\)</span> and other parameters allows public health officials to prepare and deploy interventions (vaccinations, quarantine, etc.) that have the best shot at minimizing the epidemic.</p>
<div class="figure" style="text-align: center"><span id="fig:ch7-ebola"></span>
<img src="QuantLife_files/figure-html/ch7-ebola-1.png" alt="Number of new cases of ebola virus infections  per week in Liberia (left) and Sierra Leone (right), time ranging from March 17, 2014 (week 1) until May 20, 2015 (week 61). Data from http://apps.who.int/gho/data/node.ebola-sitrep." width="50%" /><img src="QuantLife_files/figure-html/ch7-ebola-2.png" alt="Number of new cases of ebola virus infections  per week in Liberia (left) and Sierra Leone (right), time ranging from March 17, 2014 (week 1) until May 20, 2015 (week 61). Data from http://apps.who.int/gho/data/node.ebola-sitrep." width="50%" />
<p class="caption">
Figure 7.6: Number of new cases of ebola virus infections per week in Liberia (left) and Sierra Leone (right), time ranging from March 17, 2014 (week 1) until May 20, 2015 (week 61). Data from <a href="http://apps.who.int/gho/data/node.ebola-sitrep" class="uri">http://apps.who.int/gho/data/node.ebola-sitrep</a>.
</p>
</div>
<div id="discussion" class="section level3" number="7.4.1">
<h3><span class="header-section-number">7.4.1</span> Discussion</h3>
<p>The following questions encourage you to think critically about modeling of infectious diseases.</p>
<ol style="list-style-type: decimal">
<li><p>What effect does changing the infection rate <span class="math inline">\(\beta\)</span> have on the basic reproductive rate? Explain the biological intuition behind this.}</p></li>
<li><p>What effect does changing the recovery rate <span class="math inline">\(\gamma\)</span> have on the basic reproductive rate? Explain the biological intuition behind this.}</p></li>
<li><p>Discuss what assumptions are made by using compartment models, and when they might be justified.}</p></li>
<li><p>Discuss the difference in assumptions in using a Markov model with Susceptible and Infected compartments compared to an ODE model with the same two compartments. Under what circumstances does it make sense to use one or the other?}</p></li>
<li><p>Read the paper  and discuss the strengths and limitations of the more complicated compartment model intended to account for human behavior.}</p></li>
</ol>
</div>
</div>
<div id="r-assignment-6" class="section level2" number="7.5">
<h2><span class="header-section-number">7.5</span> R Assignment</h2>
<div class="sourceCode" id="cb222"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb222-1"><a href="graphical-analysis-of-ordinary-differential-equations.html#cb222-1" aria-hidden="true"></a><span class="co"># Define the function:</span></span>
<span id="cb222-2"><a href="graphical-analysis-of-ordinary-differential-equations.html#cb222-2" aria-hidden="true"></a>DefFunk &lt;-<span class="st"> </span><span class="cf">function</span> (x,a,b){</span>
<span id="cb222-3"><a href="graphical-analysis-of-ordinary-differential-equations.html#cb222-3" aria-hidden="true"></a>  ans &lt;-<span class="st"> </span>a<span class="op">*</span>x<span class="op">^</span><span class="dv">2</span><span class="op">-</span>b</span>
<span id="cb222-4"><a href="graphical-analysis-of-ordinary-differential-equations.html#cb222-4" aria-hidden="true"></a>  <span class="kw">return</span>(ans)</span>
<span id="cb222-5"><a href="graphical-analysis-of-ordinary-differential-equations.html#cb222-5" aria-hidden="true"></a>}  </span>
<span id="cb222-6"><a href="graphical-analysis-of-ordinary-differential-equations.html#cb222-6" aria-hidden="true"></a>a &lt;-<span class="st"> </span><span class="dv">1</span></span>
<span id="cb222-7"><a href="graphical-analysis-of-ordinary-differential-equations.html#cb222-7" aria-hidden="true"></a>b &lt;-<span class="st"> </span><span class="dv">4</span></span>
<span id="cb222-8"><a href="graphical-analysis-of-ordinary-differential-equations.html#cb222-8" aria-hidden="true"></a>x&lt;-<span class="kw">seq</span>(<span class="op">-</span><span class="dv">5</span>,<span class="dv">5</span>,<span class="fl">0.1</span>) <span class="co"># define the array of values of x</span></span>
<span id="cb222-9"><a href="graphical-analysis-of-ordinary-differential-equations.html#cb222-9" aria-hidden="true"></a>y&lt;-<span class="kw">DefFunk</span>(x,a,b) <span class="co"># calculate the values of y using a function</span></span>
<span id="cb222-10"><a href="graphical-analysis-of-ordinary-differential-equations.html#cb222-10" aria-hidden="true"></a><span class="kw">plot</span>(x,y,<span class="dt">t=</span><span class="st">&quot;l&quot;</span>,<span class="dt">xlab=</span><span class="st">&quot;x&quot;</span>, <span class="dt">ylab=</span><span class="st">&quot;dx/dt&quot;</span>) <span class="co"># plot the function</span></span>
<span id="cb222-11"><a href="graphical-analysis-of-ordinary-differential-equations.html#cb222-11" aria-hidden="true"></a><span class="kw">abline</span>(<span class="dv">0</span>,<span class="dv">0</span>) <span class="co"># draw a line for y=0</span></span></code></pre></div>
<p><img src="QuantLife_files/figure-html/unnamed-chunk-131-1.png" width="672" /></p>
<p>Notice that I used two input variables into the defining function (a and b) as parameters that can be changed <em>outside</em> the function. This is good coding practice - the best way to use a function is by changing its inputs, not monkeying with its internal code.</p>
<p>After qualitative analysis, you will check whether solutions behave in the predicted way by running Forward Euler to calculate the numerical solution.</p>
<div id="logistic-population-model" class="section level3" number="7.5.1">
<h3><span class="header-section-number">7.5.1</span> logistic population model</h3>
<p>This is the logistic model of population growth, with P representing population size, r is the growth rate parameter, and K is the carrying capacity parameter; P is measured in thousands, and time is measured in years.
<span class="math display">\[ \frac{dP}{dt} = rP(1-P/K) \]</span></p>
<ol style="list-style-type: decimal">
<li><ol style="list-style-type: lower-alpha">
<li>For the values of r=0.3 and K=40, plot the graph of the defining function (right-hand side of the ODE) in R over some interval that includes all zeros of the function. Based on the graph, find the equilibria of the ODE, determine their stability, and predict the behavior of the solution for the following initial values: P(0) = 1; P(0) = 39; P(0) = 20.</li>
</ol></li>
</ol>
<div class="sourceCode" id="cb223"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb223-1"><a href="graphical-analysis-of-ordinary-differential-equations.html#cb223-1" aria-hidden="true"></a><span class="co">#YOUR CODE HERE</span></span></code></pre></div>
<p>YOUR ANSWERS HERE</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Uses the Forward Euler method to calculate the numeric solution of the logistic ODE for any given values of r and K (they should be inputs into your defining function). Use this script to solve the logistic ODE with parameters r=0.3 and K=40, with a small time step (e.g. dt=0.1) and the following initial values: P(0) = 1; P(0) = 39; P(0) = 20. Calculate the numerical solutions of the ODE over a sufficiently large time Tmax to observe convergence, and plot all three in the same figure. Do the solution plots look consistent with your prediction in question a?</li>
</ol>
<div class="sourceCode" id="cb224"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb224-1"><a href="graphical-analysis-of-ordinary-differential-equations.html#cb224-1" aria-hidden="true"></a><span class="co">#YOUR CODE HERE</span></span></code></pre></div>
<p>YOUR ANSWERS HERE</p>
<ol start="2" style="list-style-type: decimal">
<li>For the values of the parameters r=0.02 and K=120, plot the graph of the defining function (right-hand side of the ODE) in R over some interval that includes all zeros of the function. Based on the graph, find the equilibria of the ODE, determine their stability, and predict the behavior of the solution for the following initial values: P(0) = 10; P(0) = 50; P(0) = 150.</li>
</ol>
<div class="sourceCode" id="cb225"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb225-1"><a href="graphical-analysis-of-ordinary-differential-equations.html#cb225-1" aria-hidden="true"></a><span class="co">#YOUR CODE HERE</span></span></code></pre></div>
<p>YOUR ANSWERS HERE</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Use the Forward Euler method to calculate the numeric solution of the logistic ODE with parameters r=0.02 and K=120 with a small time step (e.g. dt=0.1) and the following initial values: P(0) = 10; P(0) = 50; P(0) = 150. Plot the numeric solutions of the ODE over a sufficiently large time Tmax to observe convergence. Do the solution plots look consistent with your prediction in question a?</li>
</ol>
<div class="sourceCode" id="cb226"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb226-1"><a href="graphical-analysis-of-ordinary-differential-equations.html#cb226-1" aria-hidden="true"></a><span class="co">#YOUR CODE HERE</span></span></code></pre></div>
<p>YOUR ANSWERS HERE</p>
<ol start="3" style="list-style-type: decimal">
<li>Let r=0.3 and K=40 and start at P(0)=1. Gradually increase dt until you see the solution behaving differently than expected. Report at what value of dt this strange behavior begins, investigate what happens for even larger time steps, and describe what happens to the solutions.</li>
</ol>
<div class="sourceCode" id="cb227"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb227-1"><a href="graphical-analysis-of-ordinary-differential-equations.html#cb227-1" aria-hidden="true"></a><span class="co">#YOUR CODE HERE</span></span></code></pre></div>
<p>YOUR ANSWERS HERE</p>
</div>
<div id="sis-model-of-infectious-disease" class="section level3" number="7.5.2">
<h3><span class="header-section-number">7.5.2</span> SIS model of infectious disease</h3>
<p>The following ODE is a simple model of an infectious epidemic with only two kinds of individuals: susceptible and infected, and where the total population size stays the same. The variable I is the fraction of individuals in the population who are infected, and the parameters beta and gamma are the infection and recovery rates, respectively; time is measured in days.
<span class="math display">\[ \frac{dI}{dt} = \beta I(1-I) - \gamma I \]</span></p>
<ol style="list-style-type: decimal">
<li><ol style="list-style-type: lower-alpha">
<li>For the values of beta = 0.4 and gamma=0.1 plot the graph of the defining function (right-hand side of the ODE) in R over the interval [0,1]. Based on the graph, find the equilibria of the ODE, determine their stability, and predict the behavior of the solution for the following initial values: I(0) = 0.01; I(0) = 0.8; I(0) = 0.5.</li>
</ol></li>
</ol>
<div class="sourceCode" id="cb228"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb228-1"><a href="graphical-analysis-of-ordinary-differential-equations.html#cb228-1" aria-hidden="true"></a><span class="co">#YOUR CODE HERE</span></span></code></pre></div>
<p>YOUR ANSWERS HERE</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Write a Forward Euler script to calculate the numeric solution of the SIS model ODE for any given values of beta and gamma (they should be inputs into your defining function). Use this script to solve the SIS model ODE with parameters beta = 0.4 and gamma=0.1 , with a small time step (e.g. dt=0.1) and the following initial values: I(0) = 0.01, I(0) = 0.5, I(0) = 0.9. Plot the numerical solutions of the ODE over a sufficiently large time Tmax to observe convergence. Report whether the epidemic persists or burns out, whether it depends on the initial value, and comment on whether the solution dynamics agrees with your prediction in question a).</li>
</ol>
<div class="sourceCode" id="cb229"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb229-1"><a href="graphical-analysis-of-ordinary-differential-equations.html#cb229-1" aria-hidden="true"></a><span class="co">#YOUR CODE HERE</span></span></code></pre></div>
<p>YOUR ANSWERS HERE</p>
<ol start="2" style="list-style-type: decimal">
<li><ol style="list-style-type: lower-alpha">
<li>For the values of beta=0.1 and gamma=0.2 plot the graph of the defining function (right-hand side of the ODE) in R over the interval [0,1]. Based on the graph, find the equilibria of the ODE, determine their stability, and predict the behavior of the solution for the following initial values: I(0) = 0.01; I(0) = 0.5; I(0) = 0.8.</li>
</ol></li>
</ol>
<div class="sourceCode" id="cb230"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb230-1"><a href="graphical-analysis-of-ordinary-differential-equations.html#cb230-1" aria-hidden="true"></a><span class="co">#YOUR CODE HERE</span></span></code></pre></div>
<p>YOUR ANSWERS HERE</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Use the Forward Euler script to solve the SIS model ODE with parameters beta=0.1 and gamma=0.2 with a small time step (e.g. dt=0.1) and the following initial values: I(0) = 0.01; I(0) = 0.8; I(0) = 0.5. Plot the numerical solutions of the ODE over a sufficiently large time Tmax to observe convergence. Report whether the epidemic persists or burns out (converges to zero), how it depends on the initial value, and comment on whether the solution dynamics agrees with your prediction in question a.</li>
</ol>
<div class="sourceCode" id="cb231"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb231-1"><a href="graphical-analysis-of-ordinary-differential-equations.html#cb231-1" aria-hidden="true"></a><span class="co">#YOUR CODE HERE</span></span></code></pre></div>
<p>YOUR ANSWERS HERE</p>
<ol start="3" style="list-style-type: decimal">
<li>For I(0)=0.5 and beta=0.1, starting with gamma=0.3, progressively decrease the value of the recovery rate gamma, and report the behavior of the numerical solution (with a small enough dt and a large enough Tmax so you can see the asymptotic behavior). Report the critical value of gamma at which the fraction of infected converges to a positive equilibrium value (the disease does not burn out.) Keep decreasing the recovery rate and report what happens to the equilibrium fraction of infected people. Does it ever get to 1?</li>
</ol>
<div class="sourceCode" id="cb232"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb232-1"><a href="graphical-analysis-of-ordinary-differential-equations.html#cb232-1" aria-hidden="true"></a><span class="co">#YOUR CODE HERE</span></span></code></pre></div>
<p>YOUR ANSWERS HERE</p>

</div>
</div>
</div>



            </section>

          </div>
        </div>
      </div>
<a href="linear-ordinary-differential-equations.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="random-variables-and-distributions.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["QuantLife.pdf", "QuantLife.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
